export type VocabWord = { id: number; word: string; meaning: string; example: string };

export const TEPS_VOCAB: VocabWord[] = [
  { id: 1, word: "auspicious", meaning: "길조의, 상서로운", example: "The clear sky was an auspicious sign for the expedition." },
  { id: 2, word: "benevolent", meaning: "자비로운, 인정 많은", example: "The benevolent donor gave millions to local charities." },
  { id: 3, word: "candid", meaning: "솔직한, 거리낌 없는", example: "She was candid about her concerns regarding the project." },
  { id: 4, word: "daunting", meaning: "위협적인, 주눅 들게 하는", example: "The sheer volume of work was daunting for the new employee." },
  { id: 5, word: "eloquent", meaning: "웅변적인, 표현력이 풍부한", example: "The lawyer gave an eloquent argument that won the jury over." },
  { id: 6, word: "fallacious", meaning: "잘못된, 오류를 범하는", example: "His argument was fallacious because it was based on false assumptions." },
  { id: 7, word: "gregarious", meaning: "사교적인, 군거하는", example: "The gregarious host made every guest feel welcome at the party." },
  { id: 8, word: "hamper", meaning: "방해하다, 지장을 주다", example: "Heavy rain will hamper rescue efforts in the flood zone." },
  { id: 9, word: "impede", meaning: "방해하다, 저지하다", example: "Bureaucratic red tape continues to impede progress." },
  { id: 10, word: "jeopardize", meaning: "위험에 빠뜨리다", example: "Leaking classified information could jeopardize national security." },
  { id: 11, word: "kindle", meaning: "불을 붙이다, 자극하다", example: "The speech kindled a passion for justice in the crowd." },
  { id: 12, word: "lethargic", meaning: "무기력한, 나른한", example: "After the long flight, she felt lethargic and could barely stay awake." },
  { id: 13, word: "meticulous", meaning: "꼼꼼한, 세심한", example: "He was meticulous in reviewing every clause of the contract." },
  { id: 14, word: "nonchalant", meaning: "태연한, 무관심한", example: "She seemed nonchalant about losing the competition." },
  { id: 15, word: "obscure", meaning: "모호한, 잘 알려지지 않은", example: "The professor quoted an obscure medieval text no one had heard of." },
  { id: 16, word: "palpable", meaning: "명백한, 만질 수 있는", example: "The tension in the room was palpable as the verdict was read." },
  { id: 17, word: "quandary", meaning: "딜레마, 곤경", example: "She was in a quandary about whether to accept the job offer." },
  { id: 18, word: "reticent", meaning: "말수가 적은, 내성적인", example: "He was reticent about sharing details of his personal life." },
  { id: 19, word: "scrutinize", meaning: "면밀히 조사하다", example: "Auditors scrutinized every financial record for irregularities." },
  { id: 20, word: "tenacious", meaning: "끈질긴, 완강한", example: "The tenacious athlete trained every day despite her injuries." },
  { id: 21, word: "ubiquitous", meaning: "어디에나 있는", example: "Smartphones have become ubiquitous in modern society." },
  { id: 22, word: "volatile", meaning: "변덕스러운, 폭발하기 쉬운", example: "Investors are wary of volatile markets that can swing wildly." },
  { id: 23, word: "wary", meaning: "조심스러운, 경계하는", example: "She was wary of strangers after the incident." },
  { id: 24, word: "xenophobia", meaning: "외국인 혐오", example: "Xenophobia can divide communities and fuel discrimination." },
  { id: 25, word: "zealous", meaning: "열성적인, 열열한", example: "The zealous activist devoted every weekend to the cause." },
  { id: 26, word: "abate", meaning: "약화되다, 줄어들다", example: "The storm finally began to abate around midnight." },
  { id: 27, word: "abdicate", meaning: "포기하다, 퇴위하다", example: "The king decided to abdicate the throne for personal reasons." },
  { id: 28, word: "aberrant", meaning: "정상에서 벗어난, 이상한", example: "His aberrant behavior alarmed his colleagues and supervisors." },
  { id: 29, word: "abhor", meaning: "혐오하다, 몹시 싫어하다", example: "She abhors any form of cruelty to animals." },
  { id: 30, word: "abject", meaning: "비참한, 굴욕적인", example: "The refugees lived in abject poverty, lacking food and shelter." },
  { id: 31, word: "abridge", meaning: "요약하다, 축약하다", example: "The publisher asked the author to abridge the novel for a younger audience." },
  { id: 32, word: "abstain", meaning: "삼가다, 자제하다", example: "He chose to abstain from alcohol during the competition season." },
  { id: 33, word: "acrimonious", meaning: "신랄한, 험악한", example: "The divorce proceedings became increasingly acrimonious." },
  { id: 34, word: "admonish", meaning: "훈계하다, 경고하다", example: "The teacher admonished the students for talking during the exam." },
  { id: 35, word: "adversary", meaning: "적, 상대", example: "He treated his political adversary with respect despite their differences." },
  { id: 36, word: "aesthetic", meaning: "미적인, 심미적인", example: "The architect had a strong aesthetic sensibility evident in every design." },
  { id: 37, word: "affluent", meaning: "부유한, 풍요로운", example: "The affluent neighborhood boasted large homes and manicured gardens." },
  { id: 38, word: "aggravate", meaning: "악화시키다, 화나게 하다", example: "Scratching the wound will only aggravate the skin irritation." },
  { id: 39, word: "alleviate", meaning: "완화시키다, 경감시키다", example: "The new medication helped alleviate her chronic back pain." },
  { id: 40, word: "ambiguous", meaning: "애매한, 모호한", example: "The wording of the contract was ambiguous and led to a dispute." },
  { id: 41, word: "ameliorate", meaning: "개선하다, 향상시키다", example: "New policies were introduced to ameliorate living conditions in the region." },
  { id: 42, word: "amicable", meaning: "우호적인, 친절한", example: "The two companies reached an amicable settlement outside of court." },
  { id: 43, word: "anachronism", meaning: "시대착오, 시대에 맞지 않는 것", example: "Using a typewriter in a modern office feels like an anachronism." },
  { id: 44, word: "animosity", meaning: "적의, 반감", example: "There was deep animosity between the two rival factions." },
  { id: 45, word: "annihilate", meaning: "전멸시키다, 완전히 파괴하다", example: "The invading army threatened to annihilate the entire city." },
  { id: 46, word: "anomaly", meaning: "변칙, 이상한 것", example: "The unusual temperature reading was flagged as an anomaly." },
  { id: 47, word: "antagonize", meaning: "적대시하다, 반감을 사다", example: "He had a habit of antagonizing his coworkers with rude remarks." },
  { id: 48, word: "apathy", meaning: "무관심, 냉담", example: "Voter apathy has led to historically low turnout in recent elections." },
  { id: 49, word: "appease", meaning: "달래다, 진정시키다", example: "The government tried to appease protesters by promising reforms." },
  { id: 50, word: "apprehensive", meaning: "걱정하는, 우려하는", example: "She was apprehensive about giving her first public speech." },
  { id: 51, word: "arbitrary", meaning: "임의적인, 독단적인", example: "The decision seemed arbitrary and lacked any logical basis." },
  { id: 52, word: "arduous", meaning: "힘든, 몹시 어려운", example: "Climbing the mountain proved to be an arduous but rewarding task." },
  { id: 53, word: "arrogant", meaning: "거만한, 오만한", example: "The arrogant CEO refused to listen to feedback from employees." },
  { id: 54, word: "articulate", meaning: "명확히 표현하다, 분명히 말하다", example: "She could articulate her ideas clearly and persuasively in any setting." },
  { id: 55, word: "ascertain", meaning: "확인하다, 알아내다", example: "Investigators worked to ascertain the cause of the accident." },
  { id: 56, word: "assiduous", meaning: "부지런한, 근면한", example: "Through assiduous practice, she became an accomplished pianist." },
  { id: 57, word: "assuage", meaning: "달래다, 완화하다", example: "He tried to assuage her fears with reassuring words." },
  { id: 58, word: "astute", meaning: "영리한, 예리한", example: "The astute investor recognized the opportunity before others did." },
  { id: 59, word: "atrocious", meaning: "잔악한, 몹시 나쁜", example: "The conditions in the prison were described as atrocious." },
  { id: 60, word: "audacious", meaning: "대담한, 뻔뻔한", example: "It was an audacious plan, but it somehow worked against all odds." },
  { id: 61, word: "augment", meaning: "증가시키다, 늘리다", example: "The company sought to augment its income through new revenue streams." },
  { id: 62, word: "avert", meaning: "피하다, 방지하다", example: "Quick action by the pilot helped avert a potential disaster." },
  { id: 63, word: "baffle", meaning: "당혹케 하다, 어리둥절하게 하다", example: "The sudden disappearance of the suspect continued to baffle detectives." },
  { id: 64, word: "belittle", meaning: "얕보다, 경시하다", example: "He had a tendency to belittle others' contributions in meetings." },
  { id: 65, word: "benign", meaning: "온화한, 양성의", example: "The doctor confirmed the tumor was benign and not dangerous." },
  { id: 66, word: "bewilder", meaning: "당혹케 하다, 혼란시키다", example: "The complex instructions bewildered the first-time user completely." },
  { id: 67, word: "bias", meaning: "편견, 편향", example: "The study was criticized for its obvious bias toward one group." },
  { id: 68, word: "blatant", meaning: "노골적인, 뻔뻔스러운", example: "His blatant disregard for the rules upset the entire team." },
  { id: 69, word: "bolster", meaning: "강화하다, 지지하다", example: "The new agreement will bolster trade relations between the two nations." },
  { id: 70, word: "brevity", meaning: "간결함, 짧음", example: "The brevity of his speech was appreciated by the tired audience." },
  { id: 71, word: "bureaucracy", meaning: "관료제, 관료주의", example: "Cutting through layers of bureaucracy delayed the project by months." },
  { id: 72, word: "cajole", meaning: "감언이설로 설득하다", example: "She cajoled her friend into joining the fitness challenge." },
  { id: 73, word: "callous", meaning: "냉담한, 무정한", example: "The callous remark left the volunteer feeling unappreciated." },
  { id: 74, word: "capricious", meaning: "변덕스러운, 예측하기 어려운", example: "The capricious weather made it hard to plan outdoor events." },
  { id: 75, word: "caustic", meaning: "신랄한, 부식성의", example: "His caustic wit often made people feel deeply uncomfortable." },
  { id: 76, word: "circumvent", meaning: "우회하다, 피하다", example: "The smugglers tried to circumvent customs using false documents." },
  { id: 77, word: "clandestine", meaning: "비밀의, 은밀한", example: "The clandestine meeting took place in an underground location." },
  { id: 78, word: "coerce", meaning: "강요하다, 억압하다", example: "He was coerced into signing the agreement under threat." },
  { id: 79, word: "cogent", meaning: "설득력 있는, 타당한", example: "She presented a cogent argument that convinced the entire board." },
  { id: 80, word: "coherent", meaning: "일관된, 논리적인", example: "Despite the complexity of the topic, his explanation was coherent." },
  { id: 81, word: "complacent", meaning: "현실에 안주하는, 자기만족의", example: "Success made the team complacent, and they stopped innovating." },
  { id: 82, word: "concede", meaning: "인정하다, 양보하다", example: "He finally conceded that his rival had performed better." },
  { id: 83, word: "condone", meaning: "묵인하다, 용서하다", example: "The school cannot condone bullying of any kind." },
  { id: 84, word: "convoluted", meaning: "복잡한, 뒤얽힌", example: "The tax code is so convoluted that most people need an accountant." },
  { id: 85, word: "copious", meaning: "풍부한, 많은", example: "She took copious notes during the three-hour lecture." },
  { id: 86, word: "corroborate", meaning: "확증하다, 뒷받침하다", example: "Witnesses came forward to corroborate his account of the incident." },
  { id: 87, word: "covert", meaning: "비밀의, 은밀한", example: "The agency conducted covert operations without public knowledge." },
  { id: 88, word: "credulous", meaning: "잘 믿는, 속기 쉬운", example: "The credulous child believed everything the magician told him." },
  { id: 89, word: "curtail", meaning: "줄이다, 삭감하다", example: "The budget was cut to curtail unnecessary spending." },
  { id: 90, word: "cynical", meaning: "냉소적인, 비꼬는", example: "After years in politics, he became cynical about real change." },
  { id: 91, word: "debilitating", meaning: "약화시키는, 쇠약하게 하는", example: "Chronic fatigue can be a debilitating condition for sufferers." },
  { id: 92, word: "deceitful", meaning: "속이는, 기만적인", example: "The deceitful salesman misled customers about the product's features." },
  { id: 93, word: "degrade", meaning: "저하시키다, 품위를 떨어뜨리다", example: "Pollutants in the river degrade the water quality over time." },
  { id: 94, word: "deliberate", meaning: "신중한, 의도적인", example: "Every word in his speech was deliberate and carefully chosen." },
  { id: 95, word: "delineate", meaning: "묘사하다, 윤곽을 그리다", example: "The report delineated the responsibilities of each department clearly." },
  { id: 96, word: "delude", meaning: "속이다, 현혹하다", example: "Don't delude yourself into thinking this problem will resolve on its own." },
  { id: 97, word: "denounce", meaning: "비난하다, 고발하다", example: "Human rights groups denounced the government's treatment of protesters." },
  { id: 98, word: "deplete", meaning: "고갈시키다, 감소시키다", example: "Years of overfishing have depleted the region's fish stocks." },
  { id: 99, word: "derogatory", meaning: "비하하는, 경멸적인", example: "Making derogatory comments in the workplace is grounds for dismissal." },
  { id: 100, word: "despondent", meaning: "낙담한, 실망한", example: "He became despondent after failing the exam for the third time." },
  { id: 101, word: "detrimental", meaning: "해로운, 손해를 끼치는", example: "Lack of sleep is detrimental to both physical and mental health." },
  { id: 102, word: "deviate", meaning: "벗어나다, 이탈하다", example: "The plane had to deviate from its planned route due to bad weather." },
  { id: 103, word: "diligent", meaning: "부지런한, 근면한", example: "A diligent student, she reviewed her notes every single evening." },
  { id: 104, word: "discern", meaning: "식별하다, 알아보다", example: "It was difficult to discern any pattern in the random data." },
  { id: 105, word: "discrepancy", meaning: "불일치, 차이", example: "Auditors noticed a discrepancy in the financial records." },
  { id: 106, word: "disdain", meaning: "경멸, 무시", example: "She looked at the cheap imitation with obvious disdain." },
  { id: 107, word: "disparage", meaning: "깎아내리다, 비하하다", example: "It is unprofessional to disparage competitors in a public forum." },
  { id: 108, word: "disparity", meaning: "불평등, 차이", example: "The report highlighted the growing disparity between rich and poor." },
  { id: 109, word: "dissuade", meaning: "단념시키다, 설득하여 그만두게 하다", example: "His friends tried to dissuade him from making such a risky investment." },
  { id: 110, word: "docile", meaning: "온순한, 다루기 쉬운", example: "The docile dog followed commands without any resistance." },
  { id: 111, word: "dogmatic", meaning: "독단적인, 교조적인", example: "His dogmatic approach left no room for alternative perspectives." },
  { id: 112, word: "dubious", meaning: "의심스러운, 불확실한", example: "The detective was dubious about the alibi the suspect provided." },
  { id: 113, word: "eccentric", meaning: "기이한, 별난", example: "The eccentric inventor filled his home with unusual contraptions." },
  { id: 114, word: "egregious", meaning: "지독한, 터무니없는", example: "The politician made an egregious error that effectively ended his career." },
  { id: 115, word: "elicit", meaning: "이끌어내다, 유도하다", example: "The therapist's question elicited an unexpected emotional response." },
  { id: 116, word: "emulate", meaning: "모방하다, 경쟁하다", example: "Young entrepreneurs often try to emulate the success of tech giants." },
  { id: 117, word: "enigmatic", meaning: "수수께끼 같은, 불가사의한", example: "The Mona Lisa's enigmatic smile has puzzled viewers for centuries." },
  { id: 118, word: "enumerate", meaning: "열거하다, 셀 수 있다", example: "The teacher asked students to enumerate the causes of World War I." },
  { id: 119, word: "ephemeral", meaning: "일시적인, 덧없는", example: "Fame can be ephemeral — here today and completely forgotten tomorrow." },
  { id: 120, word: "equivocal", meaning: "모호한, 애매한", example: "His equivocal response satisfied no one at the press conference." },
  { id: 121, word: "erratic", meaning: "불규칙한, 변덕스러운", example: "The company's erratic performance made investors increasingly nervous." },
  { id: 122, word: "erudite", meaning: "박학한, 학식이 높은", example: "The erudite professor quoted sources from five different languages." },
  { id: 123, word: "estrange", meaning: "사이를 멀리하다, 소외시키다", example: "Years of conflict had estranged the two brothers from each other." },
  { id: 124, word: "exacerbate", meaning: "악화시키다, 심화시키다", example: "Lack of communication only exacerbated the misunderstanding between them." },
  { id: 125, word: "exorbitant", meaning: "터무니없이 비싼, 과도한", example: "The hotel charged an exorbitant fee for a very basic room." },
  { id: 126, word: "expedient", meaning: "편의적인, 실용적인", example: "It was expedient to accept the offer, even if it was not ideal." },
  { id: 127, word: "expedite", meaning: "신속히 처리하다, 촉진하다", example: "The courier service was hired to expedite the delivery of documents." },
  { id: 128, word: "exquisite", meaning: "정교한, 매우 아름다운", example: "The jeweler crafted an exquisite necklace set with rare gems." },
  { id: 129, word: "extravagant", meaning: "사치스러운, 낭비하는", example: "She threw an extravagant party with live music and catered food." },
  { id: 130, word: "fabricate", meaning: "날조하다, 조작하다", example: "He fabricated an alibi that quickly fell apart under questioning." },
  { id: 131, word: "fathom", meaning: "이해하다, 헤아리다", example: "It is hard to fathom the scale of destruction caused by the earthquake." },
  { id: 132, word: "fervent", meaning: "열렬한, 열정적인", example: "She was a fervent supporter of equal rights for all citizens." },
  { id: 133, word: "flagrant", meaning: "노골적인, 심각한", example: "The referee penalized the player for a flagrant foul." },
  { id: 134, word: "flatter", meaning: "아첨하다, 칭찬하다", example: "He flattered his boss by praising every minor decision she made." },
  { id: 135, word: "fluctuate", meaning: "변동하다, 오르내리다", example: "Currency exchange rates fluctuate based on daily economic conditions." },
  { id: 136, word: "forthright", meaning: "직접적인, 솔직한", example: "He was forthright about the challenges the project would face." },
  { id: 137, word: "fortify", meaning: "강화하다, 요새화하다", example: "The soldiers worked overnight to fortify their defensive position." },
  { id: 138, word: "foster", meaning: "조장하다, 촉진하다", example: "Good teachers foster a genuine love of learning in their students." },
  { id: 139, word: "fraught", meaning: "가득 찬, ~로 인해 걱정되는", example: "The negotiations were fraught with tension and repeated setbacks." },
  { id: 140, word: "frivolous", meaning: "경박한, 사소한", example: "The judge dismissed the case as frivolous and without merit." },
  { id: 141, word: "frugal", meaning: "절약하는, 검소한", example: "Living a frugal lifestyle helped her save enough to retire early." },
  { id: 142, word: "futile", meaning: "무익한, 효과 없는", example: "It was futile to argue with someone who refused to listen." },
  { id: 143, word: "garrulous", meaning: "수다스러운, 말이 많은", example: "The garrulous tour guide talked nonstop for three hours." },
  { id: 144, word: "genuine", meaning: "진정한, 진짜의", example: "Her concern for the community seemed genuine, not performative." },
  { id: 145, word: "gullible", meaning: "쉽게 속는, 잘 믿는", example: "The gullible tourist was easily tricked into buying a fake souvenir." },
  { id: 146, word: "hackneyed", meaning: "진부한, 식상한", example: "The speech was full of hackneyed phrases that bored the audience." },
  { id: 147, word: "haphazard", meaning: "무계획적인, 되는 대로의", example: "The boxes were arranged in a haphazard manner across the floor." },
  { id: 148, word: "heretical", meaning: "이단적인, 반정통적인", example: "His heretical views on the matter shocked the conservative committee." },
  { id: 149, word: "hypocritical", meaning: "위선적인", example: "It was hypocritical to preach honesty while hiding the truth." },
  { id: 150, word: "idiosyncratic", meaning: "특이한, 독특한", example: "His idiosyncratic style of painting attracted both praise and criticism." },
  { id: 151, word: "imminent", meaning: "임박한, 곧 일어날", example: "Scientists warned of an imminent volcanic eruption in the region." },
  { id: 152, word: "impartial", meaning: "공정한, 편견 없는", example: "The judge must remain impartial and not favor either side." },
  { id: 153, word: "impertinent", meaning: "버릇없는, 무례한", example: "The child's impertinent remarks embarrassed his parents greatly." },
  { id: 154, word: "inadvertent", meaning: "우연한, 부주의한", example: "He made an inadvertent error while filling out the tax form." },
  { id: 155, word: "incessant", meaning: "끊임없는, 계속되는", example: "The incessant noise from the construction site was unbearable." },
  { id: 156, word: "incite", meaning: "자극하다, 선동하다", example: "The speech was intended to incite the crowd to peaceful protest." },
  { id: 157, word: "incongruous", meaning: "어울리지 않는, 부조화의", example: "A tuxedo at a beach party would look completely incongruous." },
  { id: 158, word: "indifferent", meaning: "무관심한, 냉담한", example: "She was indifferent to criticism, focusing only on her goals." },
  { id: 159, word: "indignant", meaning: "분개한, 화가 난", example: "He was indignant when accused of cheating on the exam." },
  { id: 160, word: "indulge", meaning: "탐닉하다, 마음껏 즐기다", example: "She allowed herself to indulge in a slice of cake on her birthday." },
  { id: 161, word: "inept", meaning: "무능한, 서투른", example: "The inept manager consistently made poor decisions for the team." },
  { id: 162, word: "inevitable", meaning: "피할 수 없는, 불가피한", example: "With such poor planning, failure seemed inevitable from the start." },
  { id: 163, word: "infer", meaning: "추론하다, 추측하다", example: "From the evidence, investigators could infer that the crime occurred at night." },
  { id: 164, word: "ingenious", meaning: "독창적인, 영리한", example: "The engineer devised an ingenious solution to the water shortage." },
  { id: 165, word: "innate", meaning: "타고난, 선천적인", example: "She had an innate talent for music that emerged in early childhood." },
  { id: 166, word: "instigate", meaning: "부추기다, 선동하다", example: "Police suspected that outside agitators had instigated the riot." },
  { id: 167, word: "intrepid", meaning: "용감한, 두려움이 없는", example: "The intrepid explorer ventured deep into uncharted territory." },
  { id: 168, word: "inundate", meaning: "침수시키다, 쇄도하다", example: "After the flood warning, the emergency line was inundated with calls." },
  { id: 169, word: "irrevocable", meaning: "되돌릴 수 없는, 취소 불가능한", example: "Once signed, the decision was irrevocable and legally binding." },
  { id: 170, word: "laborious", meaning: "힘든, 고된", example: "Translating the ancient text was a laborious but fascinating process." },
  { id: 171, word: "laconic", meaning: "간결한, 말이 적은", example: "His laconic reply of 'No' ended the conversation immediately." },
  { id: 172, word: "languid", meaning: "나른한, 기운 없는", example: "She moved with a languid grace that suggested calm confidence." },
  { id: 173, word: "latent", meaning: "잠재적인, 숨어 있는", example: "The patient showed no symptoms, but the virus was still latent in the body." },
  { id: 174, word: "laudable", meaning: "칭찬할 만한, 훌륭한", example: "Her efforts to clean up the neighborhood were truly laudable." },
  { id: 175, word: "legitimate", meaning: "합법적인, 정당한", example: "The company had a legitimate reason to request the documents." },
  { id: 176, word: "lenient", meaning: "관대한, 너그러운", example: "Critics argued that the judge was too lenient with the defendant." },
  { id: 177, word: "lucid", meaning: "명료한, 이해하기 쉬운", example: "Even at 90, she remained lucid and sharp in her thinking." },
  { id: 178, word: "lure", meaning: "유혹하다, 꾀다", example: "The promise of quick profits was used to lure unsuspecting investors." },
  { id: 179, word: "malicious", meaning: "악의적인, 심술궂은", example: "The malicious email was designed to steal personal information." },
  { id: 180, word: "manifest", meaning: "명백히 하다, 나타내다", example: "His anxiety began to manifest in physical symptoms like trembling." },
  { id: 181, word: "meager", meaning: "빈약한, 부족한", example: "The survivors lived on a meager diet of rice and water." },
  { id: 182, word: "mediate", meaning: "중재하다, 조정하다", example: "A neutral third party was brought in to mediate the dispute." },
  { id: 183, word: "menacing", meaning: "위협적인, 불길한", example: "The dark clouds formed a menacing backdrop over the city." },
  { id: 184, word: "mitigate", meaning: "완화하다, 경감하다", example: "Green spaces can help mitigate the effects of urban heat islands." },
  { id: 185, word: "mundane", meaning: "평범한, 세속적인", example: "He longed for adventure, tired of his mundane daily routine." },
  { id: 186, word: "negligent", meaning: "부주의한, 태만한", example: "The negligent driver failed to check his mirrors before turning." },
  { id: 187, word: "notorious", meaning: "악명 높은, 유명한", example: "The city became notorious for its high crime rate in the 1980s." },
  { id: 188, word: "nurture", meaning: "양육하다, 육성하다", example: "It takes time and patience to nurture genuine talent in young students." },
  { id: 189, word: "oblivious", meaning: "알아채지 못하는, 잊어버린", example: "She was oblivious to the chaos around her, lost in her book." },
  { id: 190, word: "obsolete", meaning: "쓸모없어진, 구식의", example: "With smartphones, paper maps have become virtually obsolete." },
  { id: 191, word: "ominous", meaning: "불길한, 나쁜 징조의", example: "The ominous silence before the storm unnerved everyone in the town." },
  { id: 192, word: "opulent", meaning: "부유한, 호화로운", example: "The opulent banquet hall was decorated with gold and crystal." },
  { id: 193, word: "ostracize", meaning: "추방하다, 따돌리다", example: "She was ostracized by her peers after refusing to join the group." },
  { id: 194, word: "paramount", meaning: "가장 중요한, 최고의", example: "Patient safety is of paramount importance in any medical setting." },
  { id: 195, word: "perfidious", meaning: "배신하는, 믿을 수 없는", example: "The perfidious ally leaked the battle plans to the enemy." },
  { id: 196, word: "permeate", meaning: "스며들다, 침투하다", example: "The smell of fresh bread permeated the entire bakery." },
  { id: 197, word: "perplexed", meaning: "당혹스러운, 어리둥절한", example: "The students were perplexed by the professor's cryptic explanation." },
  { id: 198, word: "persevere", meaning: "인내하다, 굴하지 않다", example: "She continued to persevere despite facing repeated rejections." },
  { id: 199, word: "pessimistic", meaning: "비관적인", example: "He was pessimistic about the chances of reaching a deal." },
  { id: 200, word: "pragmatic", meaning: "실용적인, 현실적인", example: "A pragmatic leader focuses on what works, not on what is ideal." },
];
