export type Option = { label: "a" | "b" | "c" | "d"; text: string };

export type Question = {
  id: number;
  part: "I" | "II";
  partLabel: string;
  passage: string;
  question: string;
  options: Option[];
  answer: "a" | "b" | "c" | "d";
  explanation?: string;
  vocabId?: number; // TEPS_VOCAB id — 연동용
};

export const questions: Question[] = [
  // ──────────────── PART I : 대화 빈칸 채우기 (Q1~20) ────────────────
  {
    id: 1, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I didn't know this song was a remake.\nB: I actually like this _____ more than the original.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "model" }, { label: "b", text: "design" }, { label: "c", text: "format" }, { label: "d", text: "version" }],
    answer: "d",
    explanation: "version은 '버전, 형태'를 뜻하며 리메이크 곡의 새로운 '버전'을 가리킬 때 쓰입니다. model/design은 제품·외형, format은 형식에 쓰입니다.",
  },
  {
    id: 2, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Should I ask about getting a club membership?\nB: Why not? It wouldn't hurt to _____.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "analyze" }, { label: "b", text: "inquire" }, { label: "c", text: "inspect" }, { label: "d", text: "appeal" }],
    answer: "b",
    explanation: "inquire는 '문의하다'라는 뜻으로 'it wouldn't hurt to inquire'는 '물어봐서 손해볼 건 없다'는 자연스러운 표현입니다. inspect는 점검, appeal은 호소·매력에 씁니다.",
  },
  {
    id: 3, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: How do I sign up for online banking?\nB: You need to visit a _____ of your bank and register in person.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "division" }, { label: "b", text: "section" }, { label: "c", text: "branch" }, { label: "d", text: "range" }],
    answer: "c",
    explanation: "branch는 '(은행·회사의) 지점'을 뜻합니다. division/section은 내부 부서, range는 범위를 나타내므로 은행 지점에는 어울리지 않습니다.",
  },
  {
    id: 4, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Does the airport bus require the exact fare?\nB: No, the driver can give you _____ for small bills.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "choice" }, { label: "b", text: "change" }, { label: "c", text: "receipts" }, { label: "d", text: "refunds" }],
    answer: "b",
    explanation: "change는 '거스름돈'을 뜻합니다. 'give change'는 거스름돈을 주다는 관용 표현입니다. receipt는 영수증, refund는 환불로 문맥에 맞지 않습니다.",
  },
  {
    id: 5, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Our team plays well one week but does horribly the next.\nB: With some practice, we'll become more _____ soon.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "coherent" }, { label: "b", text: "adamant" }, { label: "c", text: "apparent" }, { label: "d", text: "consistent" }],
    answer: "d",
    explanation: "consistent는 '일관된'이라는 뜻으로 '잘하다 못하다'를 반복하는 팀이 '안정적으로' 되는 것을 표현합니다. coherent는 논리적 일관성, adamant는 완강함, apparent는 명백함입니다.",
  },
  {
    id: 6, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Can you _____ me to the nearest post office?\nB: It's around the corner on your right.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "return" }, { label: "b", text: "direct" }, { label: "c", text: "locate" }, { label: "d", text: "teach" }],
    answer: "b",
    explanation: "direct someone to a place는 '~에게 길을 안내하다'는 뜻의 관용 표현입니다. locate는 위치를 찾다, return은 돌아가다로 길을 안내하는 표현에 맞지 않습니다.",
  },
  {
    id: 7, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Your business is doing well!\nB: Thanks. I never thought it would be such a(n) _____ endeavor.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "lucrative" }, { label: "b", text: "vicarious" }, { label: "c", text: "equitable" }, { label: "d", text: "affordable" }],
    answer: "a",
    explanation: "lucrative는 '수익성 있는, 돈이 되는'이라는 뜻입니다. vicarious는 대리의, equitable은 공정한, affordable은 저렴한이라는 뜻으로 수익성을 표현할 수 없습니다.",
  },
  {
    id: 8, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I was sure the Gators were going to lose the game.\nB: I know. I can't believe they _____ a victory.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "took over" }, { label: "b", text: "pulled off" }, { label: "c", text: "cheered up" }, { label: "d", text: "got through" }],
    answer: "b",
    explanation: "pull off는 '(어려운 일을) 해내다'는 뜻의 구동사입니다. take over는 인계받다, cheer up은 기운 내다, get through는 통과하다·극복하다로 승리를 '해냈다'는 의미에는 맞지 않습니다.",
  },
  {
    id: 9, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Huge projects don't seem to overwhelm Jenny.\nB: Yeah, she's _____ by challenges.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "undaunted" }, { label: "b", text: "overlooked" }, { label: "c", text: "exacerbated" }, { label: "d", text: "disconcerted" }],
    answer: "a",
    explanation: "undaunted는 '굴하지 않는, 기죽지 않는'이라는 뜻입니다. 도전에 '기죽지 않는다'는 앞 문장과 자연스럽게 연결됩니다. disconcerted는 당황한, exacerbated는 악화된 뜻입니다.",
  },
  {
    id: 10, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I had to pay $10 to park for 20 minutes!\nB: Parking downtown costs an _____ amount of money.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "illustrious" }, { label: "b", text: "exorbitant" }, { label: "c", text: "extraneous" }, { label: "d", text: "inadvertent" }],
    answer: "b",
    explanation: "exorbitant는 '터무니없이 비싼'이라는 뜻으로 20분 주차에 $10이라는 황당한 요금에 잘 어울립니다. illustrious는 명성 있는, extraneous는 관련 없는, inadvertent는 실수로 한이라는 뜻입니다.",
  },
  {
    id: 11, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I accidentally sent the wrong file to the client.\nB: Don't panic. You can _____ the situation by sending the correct one right away.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "handle" }, { label: "b", text: "remedy" }, { label: "c", text: "correct" }, { label: "d", text: "fix" }],
    answer: "b",
    explanation: "remedy는 '(상황을) 바로잡다, 개선하다'는 뜻으로 실수로 생긴 나쁜 상황을 해결하는 데 자연스럽습니다. correct/fix도 유사하지만 TEPS에서는 remedy가 더 격식 있는 정답입니다.",
  },
  {
    id: 12, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The weather has been awful lately.\nB: Yes, it really _____ a damper on our outdoor plans.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "put" }, { label: "b", text: "cast" }, { label: "c", text: "placed" }, { label: "d", text: "set" }],
    answer: "a",
    explanation: "'put a damper on'은 '~의 흥을 깨다, 분위기를 망치다'는 고정 관용구입니다. cast/place/set은 이 관용구에 쓰이지 않습니다.",
  },
  {
    id: 13, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The presentation went much better than expected.\nB: I know. The audience was completely _____ by your ideas.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "gripped" }, { label: "b", text: "hooked" }, { label: "c", text: "captivated" }, { label: "d", text: "attracted" }],
    answer: "c",
    explanation: "captivated by는 '~에 완전히 매료된'이라는 뜻으로 청중이 발표에 완전히 빠져든 상태를 표현합니다. gripped/hooked도 유사하지만 수동태 'captivated by'가 청중 반응에 가장 자연스럽습니다.",
  },
  {
    id: 14, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Why did they cancel the construction project?\nB: Budget cuts. The city just can't _____ the expense right now.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "support" }, { label: "b", text: "afford" }, { label: "c", text: "handle" }, { label: "d", text: "manage" }],
    answer: "b",
    explanation: "'cannot afford'는 '~할 여유(돈)가 없다'는 관용 표현입니다. support/handle/manage도 부담을 나타낼 수 있지만, 비용 관련 맥락에서는 afford가 자연스러운 선택입니다.",
  },
  {
    id: 15, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: How did the negotiations go?\nB: Not well. The two sides couldn't _____ an agreement.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "reach" }, { label: "b", text: "make" }, { label: "c", text: "come to" }, { label: "d", text: "settle" }],
    answer: "a",
    explanation: "'reach an agreement'는 '합의에 도달하다'는 가장 일반적인 콜로케이션입니다. come to an agreement도 가능하지만, TEPS에서 'couldn't _____ an agreement' 형태에선 reach가 정답입니다.",
  },
  {
    id: 16, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The new employee seems to struggle with teamwork.\nB: Yes, she tends to _____ herself from the group.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "separate" }, { label: "b", text: "remove" }, { label: "c", text: "isolate" }, { label: "d", text: "distance" }],
    answer: "c",
    explanation: "isolate oneself는 '스스로를 고립시키다'는 재귀 표현으로 팀에서 혼자 떨어져 있는 상황에 가장 적합합니다. separate/distance도 유사하지만 사회적 고립을 나타낼 때는 isolate가 관용적입니다.",
  },
  {
    id: 17, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: How did the interview go?\nB: Terribly. I was so nervous I couldn't _____ my thoughts properly.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "express" }, { label: "b", text: "articulate" }, { label: "c", text: "convey" }, { label: "d", text: "communicate" }],
    answer: "b",
    explanation: "articulate는 '(생각을) 명확하게 말로 표현하다'는 뜻으로, 긴장해서 말이 제대로 안 나오는 상황에 가장 정확한 단어입니다. express/convey도 유사하지만 articulate가 '언어적 명확성'을 강조합니다.",
  },
  {
    id: 18, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The community garden project has been a great success.\nB: Yes, it has really _____ the local community together.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "gathered" }, { label: "b", text: "brought" }, { label: "c", text: "united" }, { label: "d", text: "joined" }],
    answer: "b",
    explanation: "'bring together'는 '~을 하나로 모으다, 결속시키다'는 관용 표현입니다. 'bring the community together'는 지역 사회를 하나로 묶는다는 자연스러운 표현입니다.",
  },
  {
    id: 19, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The CEO's speech was incredibly powerful.\nB: It was. He really _____ a chord with the employees.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "hit" }, { label: "b", text: "struck" }, { label: "c", text: "touched" }, { label: "d", text: "made" }],
    answer: "b",
    explanation: "'strike a chord'는 '공감을 얻다, 감동을 주다'는 관용 표현입니다. hit a chord라고도 하지만 정석은 struck(strike의 과거형)입니다. touched/made a chord는 쓰이지 않습니다.",
  },
  {
    id: 20, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The sales team exceeded their target this quarter!\nB: Great news. They've really been _____ themselves lately.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "outdoing" }, { label: "b", text: "surpassing" }, { label: "c", text: "pushing" }, { label: "d", text: "bettering" }],
    answer: "a",
    explanation: "'outdo oneself'는 '자신의 한계를 뛰어넘다, 이전보다 잘하다'는 관용 표현입니다. surpass oneself도 가능하지만 outdo oneself가 더 관용적입니다. push/better oneself는 다른 의미입니다.",
  },

  // ──────────────── PART II : 문장 빈칸 채우기 (Q21~60) ────────────────
  {
    id: 21, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Antibiotics are often prescribed to help _____ infections.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "cure" }, { label: "b", text: "relax" }, { label: "c", text: "mend" }, { label: "d", text: "repair" }],
    answer: "a",
    explanation: "cure infections는 '감염을 치료하다'는 의학적 표현입니다. mend는 물건·관계를 고치는 데 쓰이고, repair는 물리적 수리에 쓰입니다. 의학적 치료에는 cure/treat가 관용적입니다.",
  },
  {
    id: 22, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Police are _____ for the man who stole three bicycles in the neighborhood.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "pushing" }, { label: "b", text: "reaching" }, { label: "c", text: "exploring" }, { label: "d", text: "searching" }],
    answer: "d",
    explanation: "'search for'는 '~을 찾다'의 관용 표현입니다. 경찰이 용의자를 수배하는 상황에 쓰이는 자연스러운 표현입니다. explore/reach/push는 이 문맥에 어울리지 않습니다.",
  },
  {
    id: 23, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The main theater has a maximum _____ of 3,000 people.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "capacity" }, { label: "b", text: "estimate" }, { label: "c", text: "potential" }, { label: "d", text: "extension" }],
    answer: "a",
    explanation: "capacity는 '수용 인원, 최대 용량'을 뜻합니다. 'maximum capacity'는 '최대 수용 인원'이라는 고정 표현입니다. potential은 가능성, estimate는 추정치를 의미합니다.",
  },
  {
    id: 24, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "To help students _____ high test scores, teachers require adequate support in the classroom.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "fulfill" }, { label: "b", text: "gather" }, { label: "c", text: "achieve" }, { label: "d", text: "perform" }],
    answer: "c",
    explanation: "'achieve high test scores'는 '높은 시험 점수를 얻다'는 관용 표현입니다. fulfill은 의무·조건을 이행하다, perform은 수행하다라는 뜻으로 점수를 '달성'할 때는 achieve가 적절합니다.",
  },
  {
    id: 25, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Students should pick up their ID cards at the administration office, where all IDs are _____.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "issued" }, { label: "b", text: "drawn" }, { label: "c", text: "served" }, { label: "d", text: "sought" }],
    answer: "a",
    explanation: "'IDs are issued'는 '신분증이 발급된다'는 표현으로 issue는 공식 문서·카드를 '발급하다'에 사용되는 관용 표현입니다. draw/serve/seek는 이 맥락에 쓰이지 않습니다.",
  },
  {
    id: 26, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The latest Marzel V250 laptop _____ improvements in speed and durability.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "affirms" }, { label: "b", text: "obtains" }, { label: "c", text: "harbors" }, { label: "d", text: "features" }],
    answer: "d",
    explanation: "feature는 제품이 특징·기능을 '포함하다, 탑재하다'는 뜻입니다. 'features improvements'는 '개선 사항을 특징으로 갖추다'는 자연스러운 표현입니다. affirm은 확언, harbor는 품다, obtain은 얻다입니다.",
  },
  {
    id: 27, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Tuition fees _____ only part of most universities' operating costs.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "grant" }, { label: "b", text: "cover" }, { label: "c", text: "spend" }, { label: "d", text: "excuse" }],
    answer: "b",
    explanation: "'cover costs'는 '비용을 충당하다'는 관용 표현입니다. grant는 허가·지원금을 주다, spend는 돈을 쓰다, excuse는 용서하다로 비용 충당에는 cover가 자연스럽습니다.",
  },
  {
    id: 28, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Although John scored below his average in Round 1, his _____ score over three rounds was one of his best ever.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "abstract" }, { label: "b", text: "adjacent" }, { label: "c", text: "congruent" }, { label: "d", text: "cumulative" }],
    answer: "d",
    explanation: "cumulative는 '누적된'이라는 뜻으로 '여러 라운드를 합산한 점수'를 표현합니다. adjacent는 인접한, congruent는 합동의, abstract는 추상적인 뜻으로 점수 맥락에 맞지 않습니다.",
  },
  {
    id: 29, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Each year, many Chinese students follow the _____ of tearing up their textbooks after taking their college entrance exams.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "conduct" }, { label: "b", text: "formula" }, { label: "c", text: "process" }, { label: "d", text: "ritual" }],
    answer: "d",
    explanation: "ritual은 '(관습적으로 행해지는) 의식, 의례'라는 뜻입니다. 매년 반복되는 상징적 행동을 가리킬 때 ritual이 적절합니다. conduct는 행동·지휘, formula는 공식, process는 과정입니다.",
  },
  {
    id: 30, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "With powerful winds, hurricanes can have _____ effects on coastal communities.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "catastrophic" }, { label: "b", text: "diminutive" }, { label: "c", text: "imperative" }, { label: "d", text: "audacious" }],
    answer: "a",
    explanation: "catastrophic은 '대재앙적인'이라는 뜻으로 허리케인이 해안 지역에 미치는 심각한 피해를 표현합니다. diminutive는 아주 작은, imperative는 필수적인, audacious는 대담한이라는 뜻입니다.",
  },
  {
    id: 31, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "A typical red blood cell _____ about 6 to 8 micrometers in diameter.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "measures" }, { label: "b", text: "evaluates" }, { label: "c", text: "calculates" }, { label: "d", text: "quantifies" }],
    answer: "a",
    explanation: "measure는 크기·길이를 '측정하다, ~의 크기가 되다'는 뜻입니다. 'measures about 6 to 8 micrometers'는 '약 6~8마이크로미터 크기이다'는 표현입니다. evaluate/calculate는 값을 평가·계산할 때 씁니다.",
  },
  {
    id: 32, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The two nations were able to _____ their differences after many rounds of talks.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "placate" }, { label: "b", text: "absolve" }, { label: "c", text: "constrict" }, { label: "d", text: "reconcile" }],
    answer: "d",
    explanation: "reconcile differences는 '이견을 조정하다, 화해시키다'는 표현입니다. placate는 달래다, absolve는 죄를 사하다, constrict는 수축시키다로 '이견을 해결하다'에는 reconcile이 적절합니다.",
  },
  {
    id: 33, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Construction on the bridge will _____ traffic headed in and out of the island until Friday.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "repel" }, { label: "b", text: "offset" }, { label: "c", text: "hinder" }, { label: "d", text: "thwart" }],
    answer: "c",
    explanation: "hinder는 '방해하다, 지연시키다'는 뜻으로 공사가 교통을 방해하는 상황에 적절합니다. repel은 격퇴하다, offset은 상쇄하다, thwart는 계획을 저지하다로 교통 방해 맥락에 맞지 않습니다.",
  },
  {
    id: 34, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The conglomerate controls so much oil that it has virtually _____ the oil industry.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "supplanted" }, { label: "b", text: "confiscated" }, { label: "c", text: "monopolized" }, { label: "d", text: "overshadowed" }],
    answer: "c",
    explanation: "monopolize는 '독점하다'는 뜻입니다. 한 대기업이 석유 산업을 사실상 '독점'하는 상황에 적합합니다. supplant는 대체하다, confiscate는 몰수하다, overshadow는 그늘을 드리우다입니다.",
  },
  {
    id: 35, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Robin Williams was such a(n) _____ actor that he could play a wide variety of roles.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "versatile" }, { label: "b", text: "tentative" }, { label: "c", text: "abundant" }, { label: "d", text: "ubiquitous" }],
    answer: "a",
    explanation: "versatile은 '다재다능한, 다용도의'라는 뜻으로 다양한 역할을 소화하는 배우를 묘사할 때 씁니다. tentative는 잠정적인, abundant는 풍부한, ubiquitous는 어디서나 볼 수 있는이라는 뜻입니다.",
  },
  {
    id: 36, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Staff members are advised to offer coupons to _____ customers with reasonable complaints.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "appease" }, { label: "b", text: "forestall" }, { label: "c", text: "condone" }, { label: "d", text: "preclude" }],
    answer: "a",
    explanation: "appease는 '(불만을 가진 사람을) 달래다'는 뜻으로 쿠폰으로 불만 고객을 달래는 상황에 적합합니다. forestall은 미리 방지하다, condone은 묵인하다, preclude는 방지하다입니다.",
  },
  {
    id: 37, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The pain caused by gallstones can be so _____ that sufferers are forced to seek emergency care.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "precarious" }, { label: "b", text: "provocative" }, { label: "c", text: "excruciating" }, { label: "d", text: "ameliorating" }],
    answer: "c",
    explanation: "excruciating은 '극도로 고통스러운'이라는 뜻으로 응급실에 갈 만큼 심한 통증을 표현합니다. precarious는 불안정한, provocative는 도발적인, ameliorating은 개선하는이라는 뜻입니다.",
  },
  {
    id: 38, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "After baking the cake, _____ a thick layer of chocolate icing on its top and sides.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "swipe" }, { label: "b", text: "smear" }, { label: "c", text: "splatter" }, { label: "d", text: "smudge" }],
    answer: "b",
    explanation: "smear는 '(크림·잼 등을) 골고루 바르다'는 뜻입니다. 아이싱을 케이크에 고르게 바르는 동작에 가장 적합합니다. splatter는 튀기다, smudge는 얼룩지게 하다, swipe는 훔치다·쓸다입니다.",
  },
  {
    id: 39, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Carl's hair was tangled and _____, as if he had not taken a shower for a week.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "dubbed" }, { label: "b", text: "gagged" }, { label: "c", text: "sapped" }, { label: "d", text: "matted" }],
    answer: "d",
    explanation: "matted는 '(머리카락이) 엉켜 뭉친'이라는 뜻입니다. tangled and matted는 한동안 씻지 않은 지저분한 머리를 묘사할 때 쓰이는 표현입니다. dubbed는 더빙된, gagged는 재갈을 물린, sapped는 약해진입니다.",
  },
  {
    id: 40, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "It was _____ of the politician to claim that the tax breaks benefited everyone when they mainly helped corporations.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "innocuous" }, { label: "b", text: "precocious" }, { label: "c", text: "ostentatious" }, { label: "d", text: "disingenuous" }],
    answer: "d",
    explanation: "disingenuous는 '(겉으로는 순진한 척하나) 불성실한, 속이는'이라는 뜻입니다. 실제 혜택과 달리 모두에게 도움이 된다고 주장하는 정치인 발언에 적합합니다. innocuous는 해롭지 않은, ostentatious는 과시적인입니다.",
  },
  {
    id: 41, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The scientist's new theory completely _____ the conventional understanding of gravity.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "altered" }, { label: "b", text: "overturned" }, { label: "c", text: "modified" }, { label: "d", text: "transformed" }],
    answer: "b",
    explanation: "overturn은 '(기존의 것을) 완전히 뒤집다'는 뜻입니다. 기존의 중력 이론을 '완전히 뒤집는' 강한 의미를 표현합니다. alter/modify는 부분 수정, transform은 변형·변화시키다로 뉘앙스가 다릅니다.",
  },
  {
    id: 42, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The documentary _____ light on the hidden lives of deep-sea creatures.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "shone" }, { label: "b", text: "cast" }, { label: "c", text: "shed" }, { label: "d", text: "threw" }],
    answer: "c",
    explanation: "'shed light on'은 '~에 빛을 비추다, ~을 밝히다'는 고정 관용구입니다. cast light on도 가능하지만 shed light on이 더 일반적인 표현입니다. shone/threw는 이 관용구에 쓰이지 않습니다.",
  },
  {
    id: 43, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The antique vase was _____ at $50,000 by the auction house.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "appraised" }, { label: "b", text: "assessed" }, { label: "c", text: "evaluated" }, { label: "d", text: "valued" }],
    answer: "a",
    explanation: "appraise는 '(전문가가 공식적으로 물건의 가치를) 감정하다'는 뜻입니다. 경매 회사가 골동품 가치를 공식 감정할 때 쓰는 단어입니다. assess/evaluate는 더 넓은 평가, value는 가치를 두다입니다.",
  },
  {
    id: 44, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "After the earthquake, volunteers _____ to help clear the debris from the streets.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "assembled" }, { label: "b", text: "gathered" }, { label: "c", text: "flocked" }, { label: "d", text: "rushed" }],
    answer: "c",
    explanation: "flock to는 '(많은 사람이) 떼 지어 몰려들다'는 뜻입니다. 자원봉사자들이 현장으로 대거 몰려드는 이미지를 강조합니다. assembled/gathered는 모이다, rushed는 급히 달려가다로 대규모 군중의 자발적 이동에는 flock이 적절합니다.",
  },
  {
    id: 45, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The company _____ a loss of $2 million in its first year of operation.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "sustained" }, { label: "b", text: "suffered" }, { label: "c", text: "incurred" }, { label: "d", text: "underwent" }],
    answer: "c",
    explanation: "'incur a loss'는 '손실을 입다'는 재무 용어에서 쓰이는 관용 표현입니다. suffered a loss도 가능하지만, 비즈니스·회계 문맥에서는 incur가 더 격식 있는 표현입니다.",
  },
  {
    id: 46, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The author's latest novel received _____ reviews from critics around the world.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "glowing" }, { label: "b", text: "brilliant" }, { label: "c", text: "outstanding" }, { label: "d", text: "exceptional" }],
    answer: "a",
    explanation: "'glowing reviews'는 '극찬의 리뷰'를 뜻하는 관용 표현입니다. brilliant/outstanding/exceptional도 좋은 의미지만, 비평의 맥락에서 '찬사 어린 평가'를 나타낼 때 glowing이 관용적입니다.",
  },
  {
    id: 47, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The factory's waste was _____ into the river, causing severe environmental damage.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "released" }, { label: "b", text: "discharged" }, { label: "c", text: "dumped" }, { label: "d", text: "poured" }],
    answer: "b",
    explanation: "'discharge waste'는 '폐수를 방류하다'는 환경 분야의 공식 표현입니다. dump는 불법 투기, pour는 붓다, release도 가능하지만 환경 규제 문맥에서는 discharge가 가장 적절한 표현입니다.",
  },
  {
    id: 48, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The politician's remarks were widely seen as _____ to minority groups.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "insulting" }, { label: "b", text: "offensive" }, { label: "c", text: "derogatory" }, { label: "d", text: "degrading" }],
    answer: "c",
    explanation: "derogatory는 '(특정 집단에 대해) 경멸적인, 비하하는'이라는 뜻으로 소수 집단에 대한 발언에 쓰이는 가장 적합한 단어입니다. offensive도 유사하지만 derogatory가 더 특정하게 집단 비하를 나타냅니다.",
  },
  {
    id: 49, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The new bridge is expected to significantly _____ traffic congestion in the downtown area.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "reduce" }, { label: "b", text: "ease" }, { label: "c", text: "relieve" }, { label: "d", text: "lessen" }],
    answer: "b",
    explanation: "'ease traffic congestion'은 '교통 혼잡을 완화하다'는 관용 표현입니다. ease는 불편함·혼잡을 서서히 완화할 때 쓰입니다. relieve/reduce/lessen도 유사하나 교통 맥락에서 ease가 가장 자연스럽습니다.",
  },
  {
    id: 50, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The company's reputation was seriously _____ by the financial scandal.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "harmed" }, { label: "b", text: "damaged" }, { label: "c", text: "tarnished" }, { label: "d", text: "ruined" }],
    answer: "c",
    explanation: "tarnish는 '(명성을) 더럽히다, 손상시키다'는 뜻으로 reputation과 자주 쓰이는 콜로케이션입니다. harmed/damaged/ruined도 가능하지만 '명성'의 맥락에서 tarnished가 가장 관용적입니다.",
  },
  {
    id: 51, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The city has been _____ rapid development over the past decade.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "experiencing" }, { label: "b", text: "undergoing" }, { label: "c", text: "facing" }, { label: "d", text: "witnessing" }],
    answer: "b",
    explanation: "'undergo rapid development'은 '급격한 발전을 겪다'는 관용 표현입니다. undergo는 변화·과정을 수동적으로 '겪다'는 뉘앙스로 development/transformation과 자주 쓰입니다. experiencing도 가능하지만 undergo가 더 격식체입니다.",
  },
  {
    id: 52, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The artist's latest work _____ a wide range of emotions in viewers.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "creates" }, { label: "b", text: "produces" }, { label: "c", text: "evokes" }, { label: "d", text: "generates" }],
    answer: "c",
    explanation: "evoke는 '(감정·기억을) 불러일으키다'는 뜻으로 예술 작품이 관람객의 감정을 자아낼 때 사용하는 관용적 표현입니다. create/produce/generate는 감정보다 사물·결과를 만들 때 씁니다.",
  },
  {
    id: 53, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The witness's testimony was crucial in _____ the suspect's innocence.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "establishing" }, { label: "b", text: "proving" }, { label: "c", text: "demonstrating" }, { label: "d", text: "confirming" }],
    answer: "a",
    explanation: "'establish innocence'는 '무고함을 입증하다'는 법적 용어에서 쓰이는 표현입니다. establish는 공식적으로 사실을 확립할 때 사용합니다. prove도 가능하지만 법정 증언 맥락에서는 establish가 더 격식적입니다.",
  },
  {
    id: 54, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The ancient ruins were _____ by archaeologists who had been searching for them for decades.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "discovered" }, { label: "b", text: "uncovered" }, { label: "c", text: "excavated" }, { label: "d", text: "unearthed" }],
    answer: "d",
    explanation: "unearth는 '(땅에 묻힌 것을) 발굴하다'는 뜻으로 고고학 발굴에 가장 정확한 표현입니다. excavate도 발굴을 의미하지만 수동태 'were excavated'는 목적어가 없어 어색합니다. unearthed가 관용적으로 적합합니다.",
  },
  {
    id: 55, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The new policy is expected to _____ tensions between the two neighboring countries.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "ease" }, { label: "b", text: "reduce" }, { label: "c", text: "alleviate" }, { label: "d", text: "diminish" }],
    answer: "c",
    explanation: "alleviate tensions는 '긴장을 완화하다'는 외교적 맥락에서 자주 쓰이는 표현입니다. ease/reduce/diminish도 유사하지만 양국 간 긴장 해소에는 alleviate이 더 격식 있고 적절합니다.",
  },
  {
    id: 56, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The reporter's investigation _____ widespread corruption within the organization.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "exposed" }, { label: "b", text: "revealed" }, { label: "c", text: "uncovered" }, { label: "d", text: "discovered" }],
    answer: "c",
    explanation: "'uncover corruption'은 '부패를 폭로하다, 밝혀내다'는 관용 표현입니다. expose/reveal도 가능하지만 기자의 탐사 보도로 숨겨진 비리를 드러낼 때는 uncover가 가장 관용적입니다.",
  },
  {
    id: 57, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The new treatment has shown great _____ in early clinical trials.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "potential" }, { label: "b", text: "promise" }, { label: "c", text: "possibility" }, { label: "d", text: "prospect" }],
    answer: "b",
    explanation: "'show great promise'는 '큰 가능성을 보이다'는 관용 표현입니다. promise는 미래의 성공 가능성을 나타냅니다. potential도 유사하지만 'show promise'가 임상 시험 결과에 더 관용적으로 쓰입니다.",
  },
  {
    id: 58, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The athlete was _____ from the competition after failing a drug test.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "excluded" }, { label: "b", text: "banned" }, { label: "c", text: "disqualified" }, { label: "d", text: "expelled" }],
    answer: "c",
    explanation: "disqualify는 '(규정 위반으로) 실격 처리하다'는 스포츠 공식 용어입니다. banned는 출전 금지, expelled는 퇴출, excluded는 제외인데, 도핑 테스트 후 공식 탈락 처리에는 disqualified가 정확합니다.",
  },
  {
    id: 59, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The new policy is designed to _____ innovation in the technology sector.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "promote" }, { label: "b", text: "encourage" }, { label: "c", text: "foster" }, { label: "d", text: "stimulate" }],
    answer: "c",
    explanation: "foster innovation는 '혁신을 육성하다, 장려하다'는 관용 표현입니다. promote/encourage/stimulate도 가능하지만 정책이 기술 혁신을 '길러낸다'는 뉘앙스로는 foster가 가장 적합합니다.",
  },
  {
    id: 60, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Despite her young age, she has a very _____ understanding of complex economic theories.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "mature" }, { label: "b", text: "sophisticated" }, { label: "c", text: "advanced" }, { label: "d", text: "deep" }],
    answer: "b",
    explanation: "sophisticated는 '(지식·사고가) 정교한, 수준 높은'이라는 뜻으로 복잡한 이론을 이해하는 능력을 표현합니다. mature는 성숙한, advanced는 발전된, deep은 깊은으로 지적 수준의 정교함을 나타낼 때는 sophisticated가 가장 적합합니다.",
  },

  // ──────────────── PART I : 추가 대화 빈칸 채우기 (Q61~80) ────────────────
  {
    id: 61, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The landlord said we have to vacate by the end of the month.\nB: That's unreasonable. We should _____ our rights.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "assert" }, { label: "b", text: "notify" }, { label: "c", text: "follow" }, { label: "d", text: "expand" }],
    answer: "a",
  },
  {
    id: 62, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Have you seen the new exhibit at the art museum?\nB: Yes! The paintings were absolutely _____.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "dazzling" }, { label: "b", text: "stifling" }, { label: "c", text: "fading" }, { label: "d", text: "straining" }],
    answer: "a",
  },
  {
    id: 63, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Why did the company _____ the product launch?\nB: There were some last-minute quality control issues.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "delay" }, { label: "b", text: "deflect" }, { label: "c", text: "detour" }, { label: "d", text: "dilute" }],
    answer: "a",
  },
  {
    id: 64, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I heard you got a promotion!\nB: Yeah, the timing was _____ since I was just about to look for a new job.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "fortunate" }, { label: "b", text: "notorious" }, { label: "c", text: "outrageous" }, { label: "d", text: "deliberate" }],
    answer: "a",
  },
  {
    id: 65, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The data in the report seems off.\nB: You're right. We need to _____ the figures before submitting.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "verify" }, { label: "b", text: "magnify" }, { label: "c", text: "compile" }, { label: "d", text: "outline" }],
    answer: "a",
  },
  {
    id: 66, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The new manager keeps changing the schedule without notice.\nB: That's really _____ for everyone on the team.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "disruptive" }, { label: "b", text: "constructive" }, { label: "c", text: "interactive" }, { label: "d", text: "productive" }],
    answer: "a",
  },
  {
    id: 67, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: She seemed calm after hearing the bad news.\nB: Yes, she really knows how to _____ her emotions in difficult moments.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "restrain" }, { label: "b", text: "provoke" }, { label: "c", text: "abandon" }, { label: "d", text: "overwhelm" }],
    answer: "a",
  },
  {
    id: 68, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Did the meeting yield any useful results?\nB: A bit. We at least _____ the main issues to focus on.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "pinpointed" }, { label: "b", text: "erased" }, { label: "c", text: "skipped" }, { label: "d", text: "withheld" }],
    answer: "a",
  },
  {
    id: 69, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The scholarship application is very competitive.\nB: Yes, only the most _____ candidates are selected.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "exceptional" }, { label: "b", text: "exhausted" }, { label: "c", text: "excessive" }, { label: "d", text: "exclusive" }],
    answer: "a",
  },
  {
    id: 70, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The contract terms are hard to understand.\nB: I know. The legal language can be very _____.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "convoluted" }, { label: "b", text: "transparent" }, { label: "c", text: "accessible" }, { label: "d", text: "straightforward" }],
    answer: "a",
  },
  {
    id: 71, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I heard they finally settled the lawsuit out of court.\nB: Good. Going to trial would have been very _____ for both sides.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "costly" }, { label: "b", text: "lenient" }, { label: "c", text: "trivial" }, { label: "d", text: "favorable" }],
    answer: "a",
  },
  {
    id: 72, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Why do you like that café so much?\nB: It has a very cozy _____ that helps me focus.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "ambiance" }, { label: "b", text: "capacity" }, { label: "c", text: "revenue" }, { label: "d", text: "logistics" }],
    answer: "a",
  },
  {
    id: 73, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The professor's lecture was very long and hard to follow.\nB: Agreed. She should _____ her key points more clearly.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "distill" }, { label: "b", text: "inflate" }, { label: "c", text: "scatter" }, { label: "d", text: "bypass" }],
    answer: "a",
  },
  {
    id: 74, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: How did you deal with such a difficult client?\nB: I remained patient and tried to _____ common ground.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "find" }, { label: "b", text: "establish" }, { label: "c", text: "uncover" }, { label: "d", text: "seek" }],
    answer: "b",
  },
  {
    id: 75, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The new policy has caused a lot of controversy.\nB: I know. The council should have _____ public feedback first.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "solicited" }, { label: "b", text: "ignored" }, { label: "c", text: "rejected" }, { label: "d", text: "imposed" }],
    answer: "a",
  },
  {
    id: 76, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Did you catch the documentary about climate change?\nB: Yes, it was very _____ and changed how I think about everyday habits.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "eye-opening" }, { label: "b", text: "tedious" }, { label: "c", text: "misleading" }, { label: "d", text: "redundant" }],
    answer: "a",
  },
  {
    id: 77, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: How does she manage to stay so calm under pressure?\nB: She has a real _____ for composure even in tough situations.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "knack" }, { label: "b", text: "flaw" }, { label: "c", text: "lapse" }, { label: "d", text: "void" }],
    answer: "a",
  },
  {
    id: 78, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The new software update really slowed down my computer.\nB: Mine too. It seems to _____ a lot of system resources.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "consume" }, { label: "b", text: "release" }, { label: "c", text: "distribute" }, { label: "d", text: "transfer" }],
    answer: "a",
  },
  {
    id: 79, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I'm worried about Jake. He's been very withdrawn lately.\nB: He mentioned he's been feeling _____ by all the expectations.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "overwhelmed" }, { label: "b", text: "encouraged" }, { label: "c", text: "stimulated" }, { label: "d", text: "invigorated" }],
    answer: "a",
  },
  {
    id: 80, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The city's new recycling initiative has been getting a lot of praise.\nB: Yes, it's a real _____ in the right direction.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "step" }, { label: "b", text: "gap" }, { label: "c", text: "block" }, { label: "d", text: "shift" }],
    answer: "a",
  },

  // ──────────────── PART II : 추가 문장 빈칸 채우기 (Q81~120) ────────────────
  {
    id: 81, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The suspect's alibi was _____ by witnesses who confirmed his whereabouts on the night of the crime.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "constructed" }, { label: "b", text: "corroborated" }, { label: "c", text: "condemned" }, { label: "d", text: "concealed" }],
    answer: "b",
  },
  {
    id: 82, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Her speech was so _____ that the audience sat in complete silence throughout.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "compelling" }, { label: "b", text: "trivial" }, { label: "c", text: "verbose" }, { label: "d", text: "mundane" }],
    answer: "a",
  },
  {
    id: 83, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The organization _____ funds from donors around the world to support disaster relief efforts.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "solicited" }, { label: "b", text: "expelled" }, { label: "c", text: "withheld" }, { label: "d", text: "diverted" }],
    answer: "a",
  },
  {
    id: 84, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The politician's comments were deemed _____ and quickly retracted by his office.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "inflammatory" }, { label: "b", text: "conciliatory" }, { label: "c", text: "neutral" }, { label: "d", text: "diplomatic" }],
    answer: "a",
  },
  {
    id: 85, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The research team _____ new data that challenged existing theories about the origins of the universe.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "stumbled upon" }, { label: "b", text: "did away with" }, { label: "c", text: "got over" }, { label: "d", text: "kept up with" }],
    answer: "a",
  },
  {
    id: 86, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The council's decision to approve the construction plan was met with significant _____ from local residents.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "opposition" }, { label: "b", text: "endorsement" }, { label: "c", text: "indifference" }, { label: "d", text: "patronage" }],
    answer: "a",
  },
  {
    id: 87, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The judge issued a _____ order preventing the defendants from leaving the country.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "restraining" }, { label: "b", text: "granting" }, { label: "c", text: "appealing" }, { label: "d", text: "waiving" }],
    answer: "a",
  },
  {
    id: 88, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The company's new line of products was designed to _____ to a younger demographic.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "cater" }, { label: "b", text: "object" }, { label: "c", text: "defer" }, { label: "d", text: "conform" }],
    answer: "a",
  },
  {
    id: 89, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "A new study found that regular exercise can _____ the effects of aging on the brain.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "mitigate" }, { label: "b", text: "accelerate" }, { label: "c", text: "duplicate" }, { label: "d", text: "alienate" }],
    answer: "a",
  },
  {
    id: 90, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The startup's aggressive marketing campaign _____ a surge in customer sign-ups within weeks.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "triggered" }, { label: "b", text: "stifled" }, { label: "c", text: "impeded" }, { label: "d", text: "delayed" }],
    answer: "a",
  },
  {
    id: 91, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The CEO's resignation sent _____ through the financial markets, causing stock prices to drop.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "shockwaves" }, { label: "b", text: "incentives" }, { label: "c", text: "subsidies" }, { label: "d", text: "accolades" }],
    answer: "a",
  },
  {
    id: 92, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Despite numerous attempts, the team failed to _____ a workable solution to the software bug.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "devise" }, { label: "b", text: "dismiss" }, { label: "c", text: "elude" }, { label: "d", text: "repeal" }],
    answer: "a",
  },
  {
    id: 93, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The charity event _____ more money than expected, allowing the foundation to fund three additional projects.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "raised" }, { label: "b", text: "wasted" }, { label: "c", text: "deducted" }, { label: "d", text: "borrowed" }],
    answer: "a",
  },
  {
    id: 94, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The new highway interchange is expected to _____ traffic flow in the metropolitan area.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "streamline" }, { label: "b", text: "complicate" }, { label: "c", text: "obstruct" }, { label: "d", text: "reverse" }],
    answer: "a",
  },
  {
    id: 95, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The negotiations broke down because neither party was willing to _____ on key demands.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "compromise" }, { label: "b", text: "escalate" }, { label: "c", text: "persist" }, { label: "d", text: "intensify" }],
    answer: "a",
  },
  {
    id: 96, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The ancient ruins were well _____ due to the dry climate, allowing historians to study them in detail.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "preserved" }, { label: "b", text: "demolished" }, { label: "c", text: "altered" }, { label: "d", text: "abandoned" }],
    answer: "a",
  },
  {
    id: 97, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "She _____ her composure despite the intense pressure from the media during the press conference.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "maintained" }, { label: "b", text: "abandoned" }, { label: "c", text: "forfeited" }, { label: "d", text: "neglected" }],
    answer: "a",
  },
  {
    id: 98, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The government's austerity measures were widely _____ as unfair to working-class families.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "condemned" }, { label: "b", text: "applauded" }, { label: "c", text: "endorsed" }, { label: "d", text: "overlooked" }],
    answer: "a",
  },
  {
    id: 99, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The musician's _____ style blended elements of jazz, classical, and electronic music.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "eclectic" }, { label: "b", text: "conventional" }, { label: "c", text: "monotonous" }, { label: "d", text: "derivative" }],
    answer: "a",
  },
  {
    id: 100, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The professor's research _____ new light on the relationship between sleep deprivation and cognitive performance.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "shed" }, { label: "b", text: "cast" }, { label: "c", text: "threw" }, { label: "d", text: "shone" }],
    answer: "a",
  },
  {
    id: 101, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The doctor advised the patient to _____ from strenuous activity for at least two weeks after the surgery.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "refrain" }, { label: "b", text: "proceed" }, { label: "c", text: "indulge" }, { label: "d", text: "engage" }],
    answer: "a",
  },
  {
    id: 102, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The novel's plot was so _____ that readers found it difficult to put the book down.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "gripping" }, { label: "b", text: "tedious" }, { label: "c", text: "superficial" }, { label: "d", text: "predictable" }],
    answer: "a",
  },
  {
    id: 103, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The team _____ their strategy after the first half, which led to a dramatic comeback victory.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "overhauled" }, { label: "b", text: "discarded" }, { label: "c", text: "duplicated" }, { label: "d", text: "concealed" }],
    answer: "a",
  },
  {
    id: 104, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The government _____ strict regulations on the import of certain agricultural products.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "imposed" }, { label: "b", text: "waived" }, { label: "c", text: "retracted" }, { label: "d", text: "bypassed" }],
    answer: "a",
  },
  {
    id: 105, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The scientist's _____ discovery earned her widespread recognition in the field of molecular biology.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "groundbreaking" }, { label: "b", text: "redundant" }, { label: "c", text: "insignificant" }, { label: "d", text: "tentative" }],
    answer: "a",
  },
  {
    id: 106, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The company's profits have been _____ declining over the past three quarters due to market saturation.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "steadily" }, { label: "b", text: "abruptly" }, { label: "c", text: "sporadically" }, { label: "d", text: "selectively" }],
    answer: "a",
  },
  {
    id: 107, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The hospital implemented new procedures to _____ the spread of the highly contagious virus.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "contain" }, { label: "b", text: "amplify" }, { label: "c", text: "stimulate" }, { label: "d", text: "overlook" }],
    answer: "a",
  },
  {
    id: 108, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The newly elected mayor promised to _____ a long-overdue renovation of the city's aging infrastructure.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "undertake" }, { label: "b", text: "abandon" }, { label: "c", text: "obstruct" }, { label: "d", text: "delay" }],
    answer: "a",
  },
  {
    id: 109, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The company's acquisition of the startup gave it _____ access to cutting-edge artificial intelligence technology.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "unprecedented" }, { label: "b", text: "restricted" }, { label: "c", text: "limited" }, { label: "d", text: "marginal" }],
    answer: "a",
  },
  {
    id: 110, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The government's new housing policy aims to make homeownership more _____ for first-time buyers.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "attainable" }, { label: "b", text: "exclusive" }, { label: "c", text: "burdensome" }, { label: "d", text: "elusive" }],
    answer: "a",
  },
  {
    id: 111, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The film director's latest work received mixed reviews, with some critics praising its ambition while others found it overly _____.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "pretentious" }, { label: "b", text: "concise" }, { label: "c", text: "accessible" }, { label: "d", text: "straightforward" }],
    answer: "a",
  },
  {
    id: 112, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The long drought _____ crops across the region, leading to a severe food shortage.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "devastated" }, { label: "b", text: "nourished" }, { label: "c", text: "enriched" }, { label: "d", text: "replenished" }],
    answer: "a",
  },
  {
    id: 113, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The committee was _____ by the sheer volume of complaints it received regarding the new regulations.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "inundated" }, { label: "b", text: "motivated" }, { label: "c", text: "reassured" }, { label: "d", text: "liberated" }],
    answer: "a",
  },
  {
    id: 114, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Despite being _____ by the initial setback, the entrepreneur persisted and eventually built a thriving business.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "undeterred" }, { label: "b", text: "emboldened" }, { label: "c", text: "encouraged" }, { label: "d", text: "motivated" }],
    answer: "a",
  },
  {
    id: 115, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The negotiators worked tirelessly to _____ a deal that would satisfy both parties.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "broker" }, { label: "b", text: "abandon" }, { label: "c", text: "contest" }, { label: "d", text: "stall" }],
    answer: "a",
  },
  {
    id: 116, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The government announced a _____ plan to reduce carbon emissions by 50% over the next decade.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "comprehensive" }, { label: "b", text: "superficial" }, { label: "c", text: "vague" }, { label: "d", text: "fragmented" }],
    answer: "a",
  },
  {
    id: 117, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The artist's work is _____ by her childhood experiences growing up in a small coastal town.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "informed" }, { label: "b", text: "dismissed" }, { label: "c", text: "restricted" }, { label: "d", text: "concealed" }],
    answer: "a",
  },
  {
    id: 118, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The merger between the two companies is expected to _____ significant cost savings through economies of scale.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "generate" }, { label: "b", text: "eliminate" }, { label: "c", text: "consume" }, { label: "d", text: "inflate" }],
    answer: "a",
  },
  {
    id: 119, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The suspect's erratic behavior during questioning led investigators to believe he was _____ something.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "concealing" }, { label: "b", text: "announcing" }, { label: "c", text: "celebrating" }, { label: "d", text: "publicizing" }],
    answer: "a",
  },
  {
    id: 120, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The charity's annual gala was a resounding success, _____ thousands of dollars for underprivileged children.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "netting" }, { label: "b", text: "wasting" }, { label: "c", text: "diverting" }, { label: "d", text: "withholding" }],
    answer: "a",
  },

  // ──────────────── 단어 연동 문제 (vocabId) ────────────────
  {
    id: 121, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Misinformation tends to _____ rapidly on social media, making it difficult for users to distinguish fact from fiction.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "diminish" }, { label: "b", text: "proliferate" }, { label: "c", text: "suppress" }, { label: "d", text: "stagnate" }],
    answer: "b",
    explanation: "proliferate는 '급증하다, 확산되다'를 뜻합니다. 잘못된 정보가 소셜 미디어에서 빠르게 퍼져나간다는 문맥에 적합합니다.",
    vocabId: 201,
  },
  {
    id: 122, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The _____ effects of prolonged stress on cardiovascular health have been confirmed by numerous clinical studies.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "beneficial" }, { label: "b", text: "trivial" }, { label: "c", text: "pernicious" }, { label: "d", text: "temporary" }],
    answer: "c",
    explanation: "pernicious는 '유해한, 해로운'을 뜻합니다. 만성 스트레스가 심혈관 건강에 해롭다는 문맥에 적합합니다.",
    vocabId: 202,
  },
  {
    id: 123, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Obesity has become increasingly _____ in urban areas, largely due to sedentary lifestyles and highly processed diets.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "rare" }, { label: "b", text: "prevalent" }, { label: "c", text: "declining" }, { label: "d", text: "regulated" }],
    answer: "b",
    explanation: "prevalent는 '널리 퍼진, 흔한'을 뜻합니다. 비만이 도시 지역에서 점점 보편화되고 있다는 문맥에 적합합니다.",
    vocabId: 204,
  },
  {
    id: 124, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Have you started working on the report yet?\nB: Not really. I keep finding excuses to _____ it.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "procrastinate" }, { label: "b", text: "complete" }, { label: "c", text: "delegate" }, { label: "d", text: "revise" }],
    answer: "a",
    explanation: "procrastinate는 '미루다, 꾸물거리다'를 뜻합니다. 보고서를 계속 미루고 있다는 문맥에 적합합니다.",
    vocabId: 205,
  },
  {
    id: 125, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "After years of conflict, the two factions were finally able to _____ their differences and form a coalition government.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "intensify" }, { label: "b", text: "reconcile" }, { label: "c", text: "publicize" }, { label: "d", text: "overlook" }],
    answer: "b",
    explanation: "reconcile은 '화해시키다, 조화시키다'를 뜻합니다. 오랜 갈등 끝에 화해하여 연립 정부를 구성한다는 문맥에 적합합니다.",
    vocabId: 206,
  },
  {
    id: 126, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The _____ pressure to meet quarterly targets eventually led several executives to resign from their positions.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "occasional" }, { label: "b", text: "manageable" }, { label: "c", text: "relentless" }, { label: "d", text: "insignificant" }],
    answer: "c",
    explanation: "relentless는 '끈질긴, 가차없는'을 뜻합니다. 분기 목표를 달성해야 한다는 끊임없는 압박을 표현하는 데 적합합니다.",
    vocabId: 207,
  },
  {
    id: 127, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Did the manager agree to extend the deadline?\nB: He was _____ at first, but eventually agreed after we explained the situation.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "eager" }, { label: "b", text: "reluctant" }, { label: "c", text: "determined" }, { label: "d", text: "delighted" }],
    answer: "b",
    explanation: "reluctant는 '내키지 않는, 꺼리는'을 뜻합니다. 처음에는 내키지 않았지만 결국 동의했다는 문맥에 적합합니다.",
    vocabId: 208,
  },
  {
    id: 128, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Despite repeated setbacks and funding shortages, the research team proved to be remarkably _____ and continued their work.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "fragile" }, { label: "b", text: "dormant" }, { label: "c", text: "resilient" }, { label: "d", text: "cautious" }],
    answer: "c",
    explanation: "resilient는 '회복력 있는, 탄력 있는'을 뜻합니다. 거듭되는 좌절에도 굴하지 않고 연구를 이어간다는 문맥에 적합합니다.",
    vocabId: 210,
  },
  {
    id: 129, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The medical school is renowned for its _____ training program, which demands exceptional dedication from every student.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "lenient" }, { label: "b", text: "arbitrary" }, { label: "c", text: "rigorous" }, { label: "d", text: "superficial" }],
    answer: "c",
    explanation: "rigorous는 '엄격한, 철저한'을 뜻합니다. 뛰어난 헌신을 요구하는 혹독한 훈련 프로그램을 묘사하는 데 적합합니다.",
    vocabId: 213,
  },
  {
    id: 130, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The national economy posted _____ growth last year, surpassing analyst forecasts by a significant margin.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "sluggish" }, { label: "b", text: "volatile" }, { label: "c", text: "marginal" }, { label: "d", text: "robust" }],
    answer: "d",
    explanation: "robust는 '강건한, 튼튼한'을 뜻합니다. 예상을 크게 웃도는 강력한 경제 성장을 표현하는 데 적합합니다.",
    vocabId: 214,
  },
  {
    id: 131, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The new regulations seem almost impossible to comply with.\nB: I agree. The standards are incredibly _____ compared to other industries.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "lenient" }, { label: "b", text: "stringent" }, { label: "c", text: "informal" }, { label: "d", text: "outdated" }],
    answer: "b",
    explanation: "stringent는 '엄격한, 까다로운'을 뜻합니다. 다른 산업과 비교해도 따르기 매우 까다로운 기준이라는 문맥에 적합합니다.",
    vocabId: 224,
  },
  {
    id: 132, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Consumer spending remained _____ throughout the first quarter, prompting analysts to revise their growth forecasts downward.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "vibrant" }, { label: "b", text: "excessive" }, { label: "c", text: "sluggish" }, { label: "d", text: "predictable" }],
    answer: "c",
    explanation: "sluggish는 '느린, 활기 없는'을 뜻합니다. 소비 지출이 부진하여 성장 전망을 하향 조정한다는 문맥에 적합합니다.",
    vocabId: 218,
  },
  {
    id: 133, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The national economy has remained largely _____ for years, with unemployment high and investment low.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "booming" }, { label: "b", text: "diversified" }, { label: "c", text: "stagnant" }, { label: "d", text: "reformed" }],
    answer: "c",
    explanation: "stagnant는 '정체된, 침체된'을 뜻합니다. 실업률은 높고 투자가 낮은 침체된 경제 상황을 표현하는 데 적합합니다.",
    vocabId: 222,
  },
  {
    id: 134, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The designer made only _____ adjustments to the original logo, so most customers didn't notice any change.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "drastic" }, { label: "b", text: "subtle" }, { label: "c", text: "visible" }, { label: "d", text: "radical" }],
    answer: "b",
    explanation: "subtle은 '미묘한, 섬세한'을 뜻합니다. 대부분의 고객이 눈치채지 못할 만큼 미세한 변경이라는 문맥에 적합합니다.",
    vocabId: 227,
  },
  {
    id: 135, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Despite her resolve to stay awake, she eventually _____ to exhaustion and fell asleep at her desk.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "refused" }, { label: "b", text: "adapted" }, { label: "c", text: "succumbed" }, { label: "d", text: "resisted" }],
    answer: "c",
    explanation: "succumb은 '굴복하다, 지다'를 뜻합니다. 버티려 했지만 결국 피로에 굴복하여 잠들었다는 문맥에 적합합니다.",
    vocabId: 228,
  },
  {
    id: 136, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The editor advised the author to cut _____ passages that added little value to the overall narrative.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "essential" }, { label: "b", text: "superfluous" }, { label: "c", text: "vivid" }, { label: "d", text: "concise" }],
    answer: "b",
    explanation: "superfluous는 '불필요한, 과잉의'를 뜻합니다. 전체 서사에 가치를 더하지 못하는 불필요한 구절을 삭제하라는 문맥에 적합합니다.",
    vocabId: 229,
  },
  {
    id: 137, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Streaming platforms have largely _____ traditional cable television as the primary source of home entertainment.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "reinforced" }, { label: "b", text: "supplanted" }, { label: "c", text: "complemented" }, { label: "d", text: "revived" }],
    answer: "b",
    explanation: "supplant는 '대체하다, 몰아내다'를 뜻합니다. 스트리밍 플랫폼이 케이블 TV를 대체했다는 문맥에 적합합니다.",
    vocabId: 230,
  },
  {
    id: 138, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The atmosphere at the funeral was incredibly moving.\nB: Yes, it was truly _____. Everyone was deeply affected.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "festive" }, { label: "b", text: "chaotic" }, { label: "c", text: "solemn" }, { label: "d", text: "lighthearted" }],
    answer: "c",
    explanation: "solemn은 '엄숙한, 진지한'을 뜻합니다. 장례식의 분위기를 묘사하며 모두가 깊이 감동받았다는 문맥에 적합합니다.",
    vocabId: 219,
  },
  {
    id: 139, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "She was a _____ advocate for civil rights and never wavered in her commitment, even under intense political pressure.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "passive" }, { label: "b", text: "reluctant" }, { label: "c", text: "staunch" }, { label: "d", text: "indifferent" }],
    answer: "c",
    explanation: "staunch는 '확고한, 완강한'을 뜻합니다. 강한 정치적 압박에도 흔들리지 않는 확고한 지지자를 묘사하는 데 적합합니다.",
    vocabId: 223,
  },
  {
    id: 140, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: You seem very calm considering how stressful work has been.\nB: I've been meditating every morning. It keeps me _____.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "anxious" }, { label: "b", text: "exhausted" }, { label: "c", text: "serene" }, { label: "d", text: "distracted" }],
    answer: "c",
    explanation: "serene은 '고요한, 평온한'을 뜻합니다. 명상 덕분에 스트레스가 많은 상황에서도 평온함을 유지한다는 문맥에 적합합니다.",
    vocabId: 217,
  },
];
