export type Option = { label: "a" | "b" | "c" | "d"; text: string };

export type Question = {
  id: number;
  part: "I" | "II" | "III";
  partLabel: string;
  passage: string;
  question: string;
  options: Option[];
  answer: "a" | "b" | "c" | "d";
  explanation?: string;
};

export const questions: Question[] = [
  // ──────────────── PART I : 대화 빈칸 채우기 (Q1~20) ────────────────
  {
    id: 1, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Why didn't you answer the phone?\nB: I _____ my car when it rang.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "washed" }, { label: "b", text: "was washing" }, { label: "c", text: "have washed" }, { label: "d", text: "have been washing" }],
    answer: "b",
    explanation: "전화가 울렸을 때(과거) 세차하던 중이었으므로 과거진행형 'was washing'이 정답입니다. 과거진행형은 과거의 한 시점에 진행 중이던 동작을 나타냅니다.",
  },
  {
    id: 2, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I heard you were looking for me earlier.\nB: I was just curious _____ you were free for lunch.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "that" }, { label: "b", text: "until" }, { label: "c", text: "whether" }, { label: "d", text: "whenever" }],
    answer: "c",
    explanation: "I was curious whether/if ~는 '~인지 궁금했다'는 표현으로 간접의문문에서 whether를 씁니다. that은 확실한 사실의 명사절, until은 '~까지', whenever는 '언제든지'로 문맥에 맞지 않습니다.",
  },
  {
    id: 3, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Are we meeting the clients at a café?\nB: Yes, that's _____ they said they wanted to see us.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "what" }, { label: "b", text: "which" }, { label: "c", text: "whom" }, { label: "d", text: "where" }],
    answer: "d",
    explanation: "'that's where they wanted to see us'는 '그곳이 바로 그들이 만나고 싶어 한 장소'라는 의미입니다. 장소를 선행사로 받는 관계부사 where가 필요합니다. that/which는 관계대명사, whom은 사람 목적격입니다.",
  },
  {
    id: 4, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The dogs are barking furiously.\nB: Yeah, they _____ have sensed something unusual.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "need" }, { label: "b", text: "shall" }, { label: "c", text: "must" }, { label: "d", text: "should" }],
    answer: "c",
    explanation: "must have p.p.는 '~이었음에 틀림없다'는 강한 추측을 나타냅니다. 개들이 맹렬히 짖는 현재 상황에서 뭔가를 감지한 게 분명하다는 논리적 추론에는 must가 적합합니다. should는 약한 추측, shall은 의지·약속입니다.",
  },
  {
    id: 5, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Has the employee performance evaluation changed?\nB: Yes, a different points system _____ now.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "is being used" }, { label: "b", text: "has been used" }, { label: "c", text: "are being used" }, { label: "d", text: "have been used" }],
    answer: "a",
    explanation: "주어 'a different points system'이 단수이므로 단수 동사 is가 필요합니다. 또한 현재 사용 중인 상황이므로 현재진행 수동태 'is being used'가 적절합니다. 'are being used'는 복수 주어에 씁니다.",
  },
  {
    id: 6, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The company offered Rob a raise to convince him to stay on.\nB: I doubt that it'll make _____.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "difference" }, { label: "b", text: "no difference" }, { label: "c", text: "any difference" }, { label: "d", text: "little difference" }],
    answer: "c",
    explanation: "'make any difference'는 'I doubt'와 함께 쓰여 '별 차이가 없을 것 같다'는 의미입니다. doubt 뒤 부정 맥락에서는 any를 씁니다. 'make no difference'를 쓰면 doubt와 이중부정이 되어 어색합니다.",
  },
  {
    id: 7, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Don't you mean the Park Plaza Hotel, not the Parker Hotel?\nB: Yes. I always _____.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "get mixed the two up" }, { label: "b", text: "get the two mixed up" }, { label: "c", text: "mix getting up the two" }, { label: "d", text: "mix up getting the two" }],
    answer: "b",
    explanation: "'get A mixed up'는 'A를 혼동하다'는 구문입니다. 'get + 목적어 + 형용사'의 어순으로 'get the two mixed up'이 올바른 구조입니다. 'get mixed the two up'은 목적어와 형용사 위치가 잘못됐습니다.",
  },
  {
    id: 8, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I can't believe I failed the math test.\nB: I would've given you some help if you _____ to accept it.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "have been willing" }, { label: "b", text: "would be willing" }, { label: "c", text: "had been willing" }, { label: "d", text: "are willing" }],
    answer: "c",
    explanation: "가정법 과거완료: 'would have + p.p.' 주절에 맞게 if절은 'had + p.p.'를 써야 합니다. 과거 사실의 반대를 가정하는 상황이므로 'had been willing'이 정답입니다.",
  },
  {
    id: 9, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: You're lucky to have a view of the Canadian Rockies.\nB: I enjoy having _____ close at hand.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "the natures" }, { label: "b", text: "a nature" }, { label: "c", text: "natures" }, { label: "d", text: "nature" }],
    answer: "d",
    explanation: "nature(자연)는 불가산 명사이므로 관사 없이 씁니다. 'have nature close at hand'는 '가까이에 자연을 두다'는 표현입니다. the nature는 특정 자연, natures/a nature는 쓰지 않습니다.",
  },
  {
    id: 10, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Did the software update solve the problems with your smartphone?\nB: It _____ at first, but they reoccurred yesterday.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "appeared" }, { label: "b", text: "appeared to" }, { label: "c", text: "appeared to do" }, { label: "d", text: "appeared doing" }],
    answer: "c",
    explanation: "'appear to do so'는 '그런 것처럼 보이다'는 표현으로 so가 앞 내용(solve the problems)을 대신합니다. 'appeared to'만으로는 문장이 불완전하고, 'appeared doing'은 비문법적입니다.",
  },
  {
    id: 11, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Has Tom finished his assignment yet?\nB: No, he _____ on it since this morning.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "works" }, { label: "b", text: "worked" }, { label: "c", text: "has been working" }, { label: "d", text: "had been working" }],
    answer: "c",
    explanation: "'since this morning'이 있으므로 현재완료진행형 'has been working'이 정답입니다. 과거의 특정 시점부터 지금까지 계속되는 행동에는 현재완료(진행)형을 씁니다. had been은 과거의 기준점이 있을 때 씁니다.",
  },
  {
    id: 12, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The conference starts at 9 AM tomorrow.\nB: Really? I wish someone _____ me earlier.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "told" }, { label: "b", text: "tells" }, { label: "c", text: "had told" }, { label: "d", text: "would tell" }],
    answer: "c",
    explanation: "'I wish + 가정법 과거완료': 과거 사실에 대한 아쉬움을 나타낼 때 'wish + had p.p.'를 씁니다. '더 일찍 알려줬더라면'이라는 과거 사실의 반대이므로 had told가 정답입니다.",
  },
  {
    id: 13, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Do you think we should take an umbrella?\nB: The forecast says there's a chance _____ rain this afternoon.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "for" }, { label: "b", text: "of" }, { label: "c", text: "to" }, { label: "d", text: "with" }],
    answer: "b",
    explanation: "'a chance of rain'은 '비가 올 가능성'을 나타내는 고정 표현입니다. chance + of + 명사/동명사가 관용적입니다. 'a chance for'는 기회를 위해, 'a chance to'는 ~할 기회로 다른 의미입니다.",
  },
  {
    id: 14, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The new restaurant downtown is supposed to be amazing.\nB: I've heard great things. The chef _____ to have trained in Paris.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "says" }, { label: "b", text: "is saying" }, { label: "c", text: "is said" }, { label: "d", text: "has said" }],
    answer: "c",
    explanation: "'is said to have trained'은 '파리에서 훈련받은 것으로 알려져 있다'는 수동 표현입니다. 'be said to + 동사원형'은 일반적인 사실의 수동 보고 표현입니다. says/has said는 능동태로 주어가 셰프 본인이어야 합니다.",
  },
  {
    id: 15, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Why didn't Sarah come to the party?\nB: She was feeling ill. Otherwise, she _____.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "would come" }, { label: "b", text: "would have come" }, { label: "c", text: "will come" }, { label: "d", text: "had come" }],
    answer: "b",
    explanation: "'Otherwise'가 과거 반사실 상황을 나타내므로 가정법 과거완료의 주절 형태 'would have + p.p.'가 필요합니다. 'would come'은 가정법 과거(현재 반사실) 주절에 씁니다.",
  },
  {
    id: 16, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Is the report ready for the meeting?\nB: Not yet. I need _____ more time to finalize it.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "a few" }, { label: "b", text: "a little" }, { label: "c", text: "few" }, { label: "d", text: "little" }],
    answer: "b",
    explanation: "time은 불가산 명사이므로 a few(가산)/few(가산) 대신 'a little'(약간의)을 씁니다. 'a little more time'은 '조금 더 시간이 필요하다'는 긍정 표현입니다. little만 쓰면 '시간이 거의 없다'는 부정 의미가 됩니다.",
  },
  {
    id: 17, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I'm not sure if we should hire him. He seems unqualified.\nB: I think we should give him a chance. He _____ a lot since we last interviewed him.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "improves" }, { label: "b", text: "improved" }, { label: "c", text: "has improved" }, { label: "d", text: "had improved" }],
    answer: "c",
    explanation: "'since we last interviewed him'이 있으므로 현재완료 'has improved'가 정답입니다. 과거의 면접 시점부터 현재까지의 변화를 나타냅니다. improved(단순과거)는 since절과 자연스럽게 연결되지 않습니다.",
  },
  {
    id: 18, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I didn't expect the meeting to go on so long.\nB: Neither _____. Let's get some coffee.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "did I" }, { label: "b", text: "I did" }, { label: "c", text: "do I" }, { label: "d", text: "I do" }],
    answer: "a",
    explanation: "'Neither + 조동사 + 주어'는 부정 동의 표현입니다. 앞 문장이 과거(didn't expect)이므로 'Neither did I'가 정답입니다. 'Neither I did'는 어순이 틀렸고, 'do I'는 시제가 맞지 않습니다.",
  },
  {
    id: 19, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I've been having trouble sleeping lately.\nB: You should avoid _____ coffee after 3 PM.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "drink" }, { label: "b", text: "to drink" }, { label: "c", text: "drinking" }, { label: "d", text: "drunk" }],
    answer: "c",
    explanation: "'avoid + 동명사(-ing)': avoid 뒤에는 동명사만 올 수 있습니다. 'avoid drinking'이 올바른 형태입니다. 'avoid to drink'는 비문법적이며, avoid는 to부정사를 목적어로 취하지 않습니다.",
  },
  {
    id: 20, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: What did the doctor say about your condition?\nB: She recommended that I _____ more regularly.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "exercise" }, { label: "b", text: "exercises" }, { label: "c", text: "exercising" }, { label: "d", text: "to exercise" }],
    answer: "a",
    explanation: "'recommend + that + 주어 + 동사원형': recommend 뒤 that절에서는 should가 생략된 동사원형(가정법 현재)을 씁니다. 따라서 'exercise'(원형)가 정답입니다. exercises는 3인칭 현재형이지만 가정법에서는 원형을 씁니다.",
  },

  // ──────────────── PART II : 문장 빈칸 채우기 (Q21~50) ────────────────
  {
    id: 21, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The requested documents should be at her hotel when Ms. Kim _____ in Seoul.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "arrives" }, { label: "b", text: "arrived" }, { label: "c", text: "will arrive" }, { label: "d", text: "will be arriving" }],
    answer: "a",
    explanation: "시간·조건 부사절에서는 미래 대신 현재시제를 씁니다. 'when Ms. Kim arrives'는 미래를 나타내지만 when절이므로 현재형 arrives가 정답입니다. will arrive는 시간 부사절에 쓸 수 없습니다.",
  },
  {
    id: 22, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Students who need extra money often look for part-time jobs to earn _____.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "one" }, { label: "b", text: "them" }, { label: "c", text: "some" }, { label: "d", text: "many" }],
    answer: "c",
    explanation: "앞의 'money'(불가산 명사)를 대신하는 대명사로 some이 적절합니다. one은 가산 단수 명사, them은 가산 복수 명사, many는 복수 명사를 대신합니다. 불가산 명사 money의 대용어는 some입니다.",
  },
  {
    id: 23, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The local economy took off after Dynaco Motors _____ their manufacturing plant to the city.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "moved" }, { label: "b", text: "is moving" }, { label: "c", text: "will move" }, { label: "d", text: "has moved" }],
    answer: "a",
    explanation: "주절 'took off'가 과거시제이고 접속사 after가 있으므로, 그 뒤 종속절도 과거 'moved'가 자연스럽습니다. 이미 완료된 과거 사건을 나타내므로 단순과거가 적합합니다.",
  },
  {
    id: 24, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The two directors have argued _____ each other for years about the organization's structure.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "from" }, { label: "b", text: "with" }, { label: "c", text: "over" }, { label: "d", text: "on" }],
    answer: "c",
    explanation: "'argue over'는 '~에 대해 논쟁하다'는 표현입니다. argue with는 '~와 말다툼하다'로 다른 의미입니다. argue from/on은 자연스럽지 않습니다. '의견 충돌의 주제'를 나타낼 때는 over를 씁니다.",
  },
  {
    id: 25, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Rising food prices, _____ with slowing consumer spending, have negatively impacted the revenues of restaurants.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "couple" }, { label: "b", text: "coupled" }, { label: "c", text: "coupling" }, { label: "d", text: "to couple" }],
    answer: "b",
    explanation: "'coupled with'는 '~와 결합하여'라는 분사구문입니다. 주절의 주어(Rising food prices)를 수식하는 분사 형태로, 과거분사 coupled가 와야 합니다. 수동 의미(food prices가 coupling되는 것)를 나타냅니다.",
  },
  {
    id: 26, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "School officials tend to focus on academic performance while paying _____ attention to social development.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "few" }, { label: "b", text: "any" }, { label: "c", text: "little" }, { label: "d", text: "much" }],
    answer: "c",
    explanation: "attention은 불가산 명사이므로 'little'(거의 없는)을 씁니다. few는 가산 복수 명사에 씁니다. 'paying little attention'은 '거의 관심을 기울이지 않다'는 부정적 표현입니다. much는 양이 많다는 뜻입니다.",
  },
  {
    id: 27, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Peppercorns _____ into a fine powder are useful for cooking.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "grind" }, { label: "b", text: "ground" }, { label: "c", text: "grinding" }, { label: "d", text: "are ground" }],
    answer: "b",
    explanation: "'peppercorns ground into powder'에서 ground는 과거분사로 명사(peppercorns)를 수식하는 분사구입니다. '갈아진(=분쇄된) 통후추'의 수동 의미로 과거분사 ground가 정답입니다. grinding은 능동 분사입니다.",
  },
  {
    id: 28, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Annie's doctor recommended that she _____ iron supplements daily.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "take" }, { label: "b", text: "takes" }, { label: "c", text: "is taking" }, { label: "d", text: "would take" }],
    answer: "a",
    explanation: "'recommend + that + 주어 + 동사원형(가정법)': recommend 뒤 that절에서는 should 생략 후 동사원형을 씁니다. 'she take'가 올바른 형태입니다. takes(현재 3인칭)는 가정법에서 쓰지 않습니다.",
  },
  {
    id: 29, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The landlord consented to let the tenant _____ so long as he finds a replacement.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "end of lease early" }, { label: "b", text: "early end of lease" }, { label: "c", text: "end the lease early" }, { label: "d", text: "early end the lease" }],
    answer: "c",
    explanation: "'let + 목적어 + 동사원형': let은 사역동사로 'let the tenant end the lease early'의 구조입니다. 목적어(the tenant) 뒤에 동사원형(end)이 와야 합니다. 'end of lease'는 명사구로 사역동사 구조에 어울리지 않습니다.",
  },
  {
    id: 30, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "A study _____ the causes of declining marriage rates found that economic instability is a major factor.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "examined" }, { label: "b", text: "examining" }, { label: "c", text: "has examined" }, { label: "d", text: "to have examined" }],
    answer: "b",
    explanation: "'A study examining the causes'에서 examining은 현재분사로 study(명사)를 수식합니다. study가 causes를 '능동적으로 조사하는' 관계이므로 현재분사 examining이 적절합니다. examined(과거분사)는 수동 의미가 됩니다.",
  },
  {
    id: 31, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Employees will be hit hard _____ the company's spending cuts be approved.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "should" }, { label: "b", text: "would" }, { label: "c", text: "might" }, { label: "d", text: "could" }],
    answer: "a",
    explanation: "'should the cuts be approved'는 if를 생략한 조건 도치 구문으로, 'if the spending cuts should be approved'와 같은 의미입니다. 이런 도치 조건절에는 should를 씁니다. would/might/could는 도치 조건절에 쓰이지 않습니다.",
  },
  {
    id: 32, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Isabel was thrilled to discover that she was one of the players who _____ a spot on the team.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "had given" }, { label: "b", text: "have given" }, { label: "c", text: "had been given" }, { label: "d", text: "have been given" }],
    answer: "d",
    explanation: "선행사 'players'가 복수이고 who절의 동사가 주어에 맞아야 합니다. '자리를 받은' 수동 의미이고 현재완료가 적절하므로 'have been given'이 정답입니다. had been given은 과거완료 수동으로 시제가 맞지 않습니다.",
  },
  {
    id: 33, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "_____ from ages 20 to 60, the study participants included people from a wide variety of backgrounds.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "Ranged" }, { label: "b", text: "Ranging" }, { label: "c", text: "To range" }, { label: "d", text: "Having ranged" }],
    answer: "b",
    explanation: "분사구문: 주어(participants)가 20~60세 범위에 '걸쳐 있는' 능동 관계이므로 현재분사 Ranging이 정답입니다. Ranged는 수동 분사, To range는 목적/결과의 부정사, Having ranged는 완료 분사로 문맥에 맞지 않습니다.",
  },
  {
    id: 34, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Many diners consider a restaurant's ambiance as _____ as the meal itself.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [
      { label: "a", text: "vital a part of the dining experience" },
      { label: "b", text: "the vital part of dining experience" },
      { label: "c", text: "part of the dining experience vital" },
      { label: "d", text: "the dining experience's vital part" },
    ],
    answer: "a",
    explanation: "'as + 형용사 + a/an + 명사 + as'의 구조입니다. 'as vital a part of ~ as'는 'as important as'와 같은 어순 규칙을 따릅니다. 형용사가 관사 앞에 위치하는 특수 어순입니다.",
  },
  {
    id: 35, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The new regulations require that all employees _____ protective equipment at all times.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "wear" }, { label: "b", text: "wears" }, { label: "c", text: "wearing" }, { label: "d", text: "to wear" }],
    answer: "a",
    explanation: "'require + that + 주어 + 동사원형': require 뒤 that절에서는 가정법(should 생략) 원형을 씁니다. 'all employees wear'가 올바른 형태입니다. wears(3인칭 현재)는 가정법 that절에 쓰지 않습니다.",
  },
  {
    id: 36, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Neither the manager nor the employees _____ aware of the upcoming changes.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "was" }, { label: "b", text: "were" }, { label: "c", text: "is" }, { label: "d", text: "are" }],
    answer: "b",
    explanation: "'neither A nor B + 동사': nor 뒤 주어(the employees)가 복수이므로 복수 동사 were가 정답입니다. 'neither A nor B' 구문에서 동사는 B에 수를 일치시킵니다.",
  },
  {
    id: 37, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The meeting has been postponed _____ next Monday due to scheduling conflicts.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "for" }, { label: "b", text: "to" }, { label: "c", text: "until" }, { label: "d", text: "by" }],
    answer: "c",
    explanation: "'postpone until ~'은 '~까지 연기하다'는 표현입니다. 'postpone to'는 드물고 비격식적입니다. 'until next Monday'는 '다음 월요일까지'라는 기한을 나타냅니다. for는 기간, by는 기한(마감)에 씁니다.",
  },
  {
    id: 38, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The team leader, along with his colleagues, _____ expected to present the findings.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "are" }, { label: "b", text: "were" }, { label: "c", text: "is" }, { label: "d", text: "have been" }],
    answer: "c",
    explanation: "'A, along with B, + 단수동사': 'along with'는 주어와 동사 수 일치에 영향을 주지 않습니다. 주어는 'The team leader'(단수)이므로 is가 정답입니다. 'A and B'라면 복수이지만 along with는 단순 부가구입니다.",
  },
  {
    id: 39, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "By the time the guests arrived, the food _____ already.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "was prepared" }, { label: "b", text: "has been prepared" }, { label: "c", text: "had been prepared" }, { label: "d", text: "is prepared" }],
    answer: "c",
    explanation: "'By the time + 과거절'에서 주절은 과거완료를 씁니다. 손님이 도착하기 전에(기준 과거 시점) 이미 음식이 준비되었으므로 과거완료 수동 'had been prepared'가 정답입니다.",
  },
  {
    id: 40, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Not only _____ the new policy costly, but it is also impractical.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "is" }, { label: "b", text: "was" }, { label: "c", text: "has been" }, { label: "d", text: "will be" }],
    answer: "a",
    explanation: "'Not only + 조동사/be + 주어': 부정어구 Not only가 문두에 오면 주어-동사 도치가 일어납니다. 현재 사실을 말하고 있으므로 'Not only is the policy costly'가 정답입니다. was는 시제, has been은 도치 구문에서 부자연스럽습니다.",
  },
  {
    id: 41, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The proposal was rejected on the grounds _____ it lacked sufficient evidence.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "which" }, { label: "b", text: "that" }, { label: "c", text: "what" }, { label: "d", text: "where" }],
    answer: "b",
    explanation: "'on the grounds that'는 '~라는 이유로'라는 고정 표현입니다. grounds 뒤에서 동격 접속사 that을 씁니다. which는 관계대명사, what은 선행사 포함 관계사, where는 장소에 씁니다.",
  },
  {
    id: 42, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "She would rather _____ at home than go to the crowded event.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "stay" }, { label: "b", text: "staying" }, { label: "c", text: "to stay" }, { label: "d", text: "stayed" }],
    answer: "a",
    explanation: "'would rather + 동사원형': would rather 뒤에는 동사원형이 옵니다. 'would rather stay'가 올바른 형태입니다. staying/to stay는 would rather와 함께 쓰이지 않습니다.",
  },
  {
    id: 43, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Despite _____ tired, she continued working until the deadline.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "feel" }, { label: "b", text: "felt" }, { label: "c", text: "feeling" }, { label: "d", text: "to feel" }],
    answer: "c",
    explanation: "'despite + 동명사(-ing)': despite 뒤에는 명사 또는 동명사가 옵니다. 'despite feeling tired'가 올바른 형태입니다. despite 뒤에 절을 쓸 수 없고, to부정사도 despite와 함께 쓰이지 않습니다.",
  },
  {
    id: 44, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "It wasn't until the investigation concluded _____ the full extent of the fraud became clear.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "when" }, { label: "b", text: "that" }, { label: "c", text: "which" }, { label: "d", text: "what" }],
    answer: "b",
    explanation: "'It wasn't until ~ that': 강조 구문 'It was not until A that B'에서 that을 씁니다. '~하고 나서야 비로소 B했다'는 의미입니다. when/which/what은 이 강조 구문에 쓰이지 않습니다.",
  },
  {
    id: 45, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Hardly _____ the building when the fire alarm went off.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "had we entered" }, { label: "b", text: "we had entered" }, { label: "c", text: "we entered" }, { label: "d", text: "did we enter" }],
    answer: "a",
    explanation: "'Hardly + had + 주어 + p.p.': 부정 부사 Hardly가 문두에 오면 주어-조동사 도치가 일어납니다. 'Hardly had we entered'가 올바른 도치 형태입니다. 도치 없는 'we had entered'는 비문법적입니다.",
  },
  {
    id: 46, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The document needs _____ before it can be submitted to the court.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "notarize" }, { label: "b", text: "to notarize" }, { label: "c", text: "notarizing" }, { label: "d", text: "to be notarized" }],
    answer: "d",
    explanation: "'need + to be p.p.': 주어(The document)가 공증을 받는 수동 관계이므로 수동태 부정사 'to be notarized'가 정답입니다. 'need notarizing'도 수동 의미이지만 'to be notarized'가 더 격식 있는 표현입니다.",
  },
  {
    id: 47, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "No sooner _____ home than it started to rain.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "I arrived" }, { label: "b", text: "had I arrived" }, { label: "c", text: "I had arrived" }, { label: "d", text: "did I arrive" }],
    answer: "b",
    explanation: "'No sooner + had + 주어 + p.p.': 부정 부사 No sooner가 문두에 오면 도치가 필요합니다. 'No sooner had I arrived home than it started to rain'이 올바른 구조입니다. 도치 없는 'I had arrived'는 비문법적입니다.",
  },
  {
    id: 48, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The company _____ operations in three new countries by the end of next year.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "will expand" }, { label: "b", text: "will have expanded" }, { label: "c", text: "is expanding" }, { label: "d", text: "expands" }],
    answer: "b",
    explanation: "'by the end of next year'는 미래의 완료 기한을 나타내므로 미래완료 'will have expanded'가 정답입니다. 미래완료는 미래의 특정 시점까지 완료될 동작을 나타냅니다. will expand는 단순 미래입니다.",
  },
  {
    id: 49, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The more time students spend reading, _____ they become at writing.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "the more skilled" }, { label: "b", text: "more skilled" }, { label: "c", text: "the most skilled" }, { label: "d", text: "most skilled" }],
    answer: "a",
    explanation: "'The + 비교급 ~, the + 비교급 ~': '~하면 할수록 더 ~하다'는 비례 구문입니다. 'the more time ~ , the more skilled'에서 두 번째 절도 'the + 비교급'이 와야 합니다. 관사 the 없이 'more skilled'만 쓰는 것은 비문법적입니다.",
  },
  {
    id: 50, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "He is one of the few scientists who _____ dedicated their entire career to this research.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "has" }, { label: "b", text: "have" }, { label: "c", text: "had" }, { label: "d", text: "having" }],
    answer: "b",
    explanation: "'one of the few scientists who + 복수동사': who의 선행사는 'scientists'(복수)이므로 복수 동사 have가 정답입니다. 'one of the + 복수명사 who'에서 who절의 동사는 복수명사에 수 일치합니다. has는 단수 동사입니다.",
  },

  // ──────────────── PART III : 오류 문장 찾기 (Q51~60) ────────────────
  {
    id: 51, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: That safari I went on in Tanzania totally exceeded my expectations.\n(b) B: What would you say was the highlight of the whole experience?\n(c) A: It probably was see a lion try unsuccessfully to chase down a zebra.\n(d) B: Amazing! I need to make time for a safari of my own.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "c",
    explanation: "(c)에서 'It probably was see'가 오류입니다. was 뒤에 동사원형 see를 쓸 수 없으며, 'It probably was seeing a lion'(동명사) 또는 'seeing a lion was probably the highlight'로 고쳐야 합니다.",
  },
  {
    id: 52, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: You look worried. Did anything happen at work today?\n(b) B: Management said one-fourth of the workers will be laid off sometime next year.\n(c) A: That's quite harsh. How are your coworkers taking it?\n(d) B: They haven't exactly been thrilled, but that's to expect.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "d",
    explanation: "(d)에서 'that's to expect'가 오류입니다. '예상할 수 있는 일이다'는 'that's to be expected'(수동 부정사)로 써야 합니다. expect는 누군가가 기대하는 것이므로 수동태가 필요합니다.",
  },
  {
    id: 53, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) Found in the tropical forests of Brazil are a dark-colored frog species called the Bruno's casque-headed frog. (b) Small but deadly, it secretes a poison from its skin estimated to be 25 times more toxic than pit-viper venom. (c) Unlike most other poisonous frogs, this one has a jaw with sharp spines that allow it to deliver a lethal bite. (d) Unsurprisingly, no predators of this extremely dangerous frog have been discovered in its natural habitat.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "a",
    explanation: "(a)에서 'a dark-colored frog species'는 단수이므로 'are' 대신 'is'가 와야 합니다. 도치 구문 'Found in ~ is/are + 주어'에서 주어(a species)가 단수이므로 is가 정답입니다.",
  },
  {
    id: 54, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) The International Academy of Astronautics has specific protocols for responding to the discovery of intelligent alien life. (b) These dictate that an observatory detecting possible signs of life must notify other observatories for independent verification. (c) If the signal is deemed genuinely, the original observatory is supposed to inform national and international officials. (d) The same observatory has the privilege of publicly announcing the news, though it will probably have already been leaked.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "c",
    explanation: "(c)에서 'deemed genuinely'가 오류입니다. deem은 보어로 형용사를 취하므로 부사 genuinely 대신 형용사 'genuine'을 써야 합니다. 'the signal is deemed genuine'이 올바른 표현입니다.",
  },
  {
    id: 55, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) Research suggests that students should reconsider the strategy of cramming for tests. (b) Sufficient periods of rest have already been shown being useful in helping people consolidate memories. (c) Now a new study shows that using rest periods to reflect on what was learned earlier further improves information retention. (d) So it seems that instead of cramming, students should take more breaks and reflect on what they have studied.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "b",
    explanation: "(b)에서 'been shown being useful'이 오류입니다. 'show + 목적어 + to be'의 수동태는 'be shown to be'여야 합니다. 'have been shown to be useful'이 올바른 표현입니다.",
  },
  {
    id: 56, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) Scientists have long sought to understand the complex relationship between diet and mental health. (b) Recent studies suggest that a diet rich in fruits and vegetables may help reduce symptoms of depression. (c) Researchers believe that the gut microbiome plays a crucial role in regulating mood and behavior. (d) However, more research is needed before definitive recommendations about diet and mental health can make.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "d",
    explanation: "(d)에서 'can make'가 오류입니다. recommendations는 '만들어지는' 수동 관계이므로 'can be made'로 써야 합니다. 주어 'recommendations'가 make의 행위자가 아니므로 수동태가 필요합니다.",
  },
  {
    id: 57, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: Have you heard about the new productivity app that everyone's been talking about?\n(b) B: Yes, I downloaded it last week and have been use it every day since.\n(c) A: Isn't it great? It's really helped me stay on top of my tasks.\n(d) B: Absolutely. I can't believe how much more organized I've become.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "b",
    explanation: "(b)에서 'have been use it'이 오류입니다. 현재완료진행형은 'have been + 동명사(-ing)'여야 하므로 'have been using it'으로 고쳐야 합니다.",
  },
  {
    id: 58, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) The rapid growth of social media has fundamentally changed the way people communicate. (b) Many individuals now rely on platforms like Instagram and Twitter to stay connected with friends. (c) However, critics argue that excessive social media use can lead to feelings of loneliness and inadequacy. (d) Parents are particularly concerned about the impact of social media on their child's mental well-being.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "d",
    explanation: "(d)에서 'their child's'가 오류입니다. 앞에서 'many individuals'(복수)를 가리키므로 복수 소유격 'their children's'로 써야 합니다. 또는 'their child'가 단수로 쓰이려면 앞 주어도 단수여야 합니다.",
  },
  {
    id: 59, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) The city council recently voted to invest in public transportation infrastructure. (b) The new metro line, which will connect the suburbs to the downtown area, is expected to open in 2026. (c) Officials hope the new system will encourage commuters switching from private vehicles to public transit. (d) If successful, the project could serve as a model for other cities facing similar transportation challenges.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "c",
    explanation: "(c)에서 'encourage commuters switching'이 오류입니다. 'encourage + 목적어 + to 부정사' 구조가 맞으므로 'encourage commuters to switch'로 고쳐야 합니다. switching(동명사/분사)은 encourage의 목적보어로 쓰이지 않습니다.",
  },
  {
    id: 60, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) The museum's latest exhibition focuses on the art of ancient Mesopotamia. (b) Many of the artifacts on display are over 4,000 years old and were discovered in modern-day Iraq. (c) The curator noted that preservation of such fragile objects require careful attention to temperature and humidity. (d) Visitors are requested not to touch any of the items on display during their visit.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "c",
    explanation: "(c)에서 주어가 'preservation'(단수 불가산명사)이므로 'require' 대신 'requires'로 써야 합니다. 'of such fragile objects'는 수식어구로 주어의 수에 영향을 주지 않습니다.",
  },

  // ──────────────── PART I : 추가 대화 빈칸 채우기 (Q61~80) ────────────────
  {
    id: 61, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Are you planning to attend the workshop next week?\nB: If I _____ finished the report by then, I'll go.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "have" }, { label: "b", text: "had" }, { label: "c", text: "will have" }, { label: "d", text: "would have" }],
    answer: "a",
    explanation: "If절에서 미래 사실을 조건으로 나타낼 때 'if + 현재완료'를 씁니다. 'If I have finished the report by then'에서 현재완료 have가 미래완료를 대신합니다. will have는 조건절에 쓰지 않으며, would have는 가정법 과거완료입니다.",
  },
  {
    id: 62, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Nobody knows who broke the window.\nB: Whoever _____ it should own up and take responsibility.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "does" }, { label: "b", text: "did" }, { label: "c", text: "had done" }, { label: "d", text: "has done" }],
    answer: "b",
    explanation: "whoever가 이끄는 절에서 '창문을 깼다'는 과거의 사실을 가리키므로 과거 시제 did가 적합합니다. whoever는 복합관계대명사로 'anyone who'의 의미이며, whoever절의 동사는 맥락에 맞는 시제를 씁니다.",
  },
  {
    id: 63, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Why is Peter refusing to join our project?\nB: He said he _____ to be involved in anything controversial.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "doesn't want" }, { label: "b", text: "hadn't wanted" }, { label: "c", text: "won't want" }, { label: "d", text: "wouldn't want" }],
    answer: "a",
    explanation: "'He said he doesn't want'는 시제 일치의 예외입니다. 지금도 여전히 사실인 상태(현재도 관여 원치 않음)는 현재 시제를 유지할 수 있습니다. 현재도 유효한 의지를 나타내므로 doesn't want가 가장 적합합니다.",
  },
  {
    id: 64, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I'm not sure how to handle this situation.\nB: Trust your instincts. You've dealt with _____ situations before.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "such" }, { label: "b", text: "so" }, { label: "c", text: "much" }, { label: "d", text: "very" }],
    answer: "a",
    explanation: "'such + (형용사) + 복수명사'는 '그런 종류의 ~'를 의미합니다. 'such situations'는 '그런 상황들'을 뜻합니다. so는 형용사·부사만 수식하며 명사 앞에 직접 쓰이지 않고, much/very는 명사를 수식할 수 없습니다.",
  },
  {
    id: 65, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I can't believe how much traffic there was this morning.\nB: I know. I _____ if I had taken the subway.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "would arrive sooner" }, { label: "b", text: "would have arrived sooner" }, { label: "c", text: "will arrive sooner" }, { label: "d", text: "arrived sooner" }],
    answer: "b",
    explanation: "if절(had taken the subway)이 생략된 가정법 과거완료 문장입니다. 과거 사실의 반대를 가정하는 주절에는 'would have + p.p.'가 필요합니다. 'would have arrived sooner'가 정답입니다. would arrive는 가정법 과거입니다.",
  },
  {
    id: 66, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I think the new rule is unfair.\nB: So do I, but there's _____ we can do about it right now.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "nothing" }, { label: "b", text: "anything" }, { label: "c", text: "everything" }, { label: "d", text: "something" }],
    answer: "a",
    explanation: "'there's nothing we can do'는 '우리가 할 수 있는 것이 없다'는 의미입니다. 긍정 동사 there's 뒤에서 부정 의미를 나타낼 때 nothing을 씁니다. 'there's anything'은 비문법적이며, everything/something은 긍정적 의미입니다.",
  },
  {
    id: 67, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: You sound exhausted. Did you sleep at all?\nB: Barely. I _____ all night trying to meet the deadline.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "worked" }, { label: "b", text: "was working" }, { label: "c", text: "have worked" }, { label: "d", text: "would work" }],
    answer: "b",
    explanation: "마감을 맞추기 위해 밤새 계속 작업하는 중이었다는 과거의 진행 동작이므로 과거진행형 was working이 적합합니다. worked(단순 과거)는 완료된 동작, have worked(현재완료)는 시제 불일치, would work는 가정이나 습관을 나타냅니다.",
  },
  {
    id: 68, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The venue was booked before we could reserve it.\nB: Next time, we should book _____ in advance.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "far" }, { label: "b", text: "much" }, { label: "c", text: "well" }, { label: "d", text: "quite" }],
    answer: "c",
    explanation: "'well in advance'는 '훨씬 미리, 충분히 이른 시점에'라는 관용 표현입니다. well은 부사로 in advance를 강조합니다. far in advance도 가능하지만 'far'는 여기 문맥에서 어색하며, much/quite는 in advance와 관용적으로 쓰이지 않습니다.",
  },
  {
    id: 69, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: We haven't received the shipment yet.\nB: It was supposed to arrive yesterday. Something _____ have gone wrong.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "need" }, { label: "b", text: "would" }, { label: "c", text: "must" }, { label: "d", text: "shall" }],
    answer: "c",
    explanation: "'must have + p.p.'는 과거 사실에 대한 강한 논리적 추측을 나타냅니다. 배송이 어제 도착했어야 했는데 오지 않았으므로 무언가 잘못됐음에 틀림없다는 강한 추론에 must가 적합합니다. would는 의지·가정, shall은 약속·의지입니다.",
  },
  {
    id: 70, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I didn't realize the project was due today!\nB: Had you checked your email, you _____ known about the deadline.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "will have" }, { label: "b", text: "would have" }, { label: "c", text: "would" }, { label: "d", text: "should" }],
    answer: "b",
    explanation: "'Had + 주어 + p.p.'는 'If + 주어 + had p.p.'의 도치형(가정법 과거완료)입니다. 주절에는 'would have + p.p.'가 와야 하므로 'would have known'이 정답입니다. will have는 미래완료, would는 단순 가정법 과거입니다.",
  },
  {
    id: 71, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Your presentation was excellent!\nB: Thank you. It took a lot of preparation, _____ it was worth it.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "so" }, { label: "b", text: "but" }, { label: "c", text: "or" }, { label: "d", text: "for" }],
    answer: "b",
    explanation: "많은 준비가 필요했지만 그만한 가치가 있었다는 역접(대조) 관계입니다. but은 역접 접속사로 'It took a lot of preparation, but it was worth it'이 자연스럽습니다. so는 결과, for는 이유, or는 선택을 나타냅니다.",
  },
  {
    id: 72, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Do you know _____ the training session begins?\nB: I believe it's at 9 sharp.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "that" }, { label: "b", text: "when" }, { label: "c", text: "where" }, { label: "d", text: "which" }],
    answer: "b",
    explanation: "'Do you know + 의문사절'에서 '언제 시작하는지'를 물어보므로 when이 적합합니다. 'at 9 sharp'라는 시간 답변이 when을 뒷받침합니다. that은 확실한 사실의 명사절, where는 장소, which는 선택을 나타냅니다.",
  },
  {
    id: 73, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I feel like I'm not making any progress.\nB: Don't be so hard on yourself. You've come _____ since you started.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "a long way" }, { label: "b", text: "long ways" }, { label: "c", text: "a ways long" }, { label: "d", text: "far long" }],
    answer: "a",
    explanation: "'come a long way'는 '많이 발전했다, 크게 성장했다'는 관용 표현입니다. 'You've come a long way since you started'는 '시작한 이후 많이 성장했다'는 의미입니다. long ways, a ways long, far long은 모두 비표준 또는 비문법적 표현입니다.",
  },
  {
    id: 74, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Did Lisa say anything about the merger?\nB: She mentioned _____ the final decision would be made this week.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "what" }, { label: "b", text: "which" }, { label: "c", text: "that" }, { label: "d", text: "whether" }],
    answer: "c",
    explanation: "'mention + that + 절'은 '~라고 언급하다'는 구조입니다. mention은 확실한 내용을 전달할 때 that절을 목적어로 취합니다. what은 의문사, which는 선택, whether는 '~인지 아닌지'의 불확실한 경우에 씁니다.",
  },
  {
    id: 75, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The project is taking much longer than expected.\nB: Let's _____ things up if we want to meet the deadline.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "speed" }, { label: "b", text: "speeding" }, { label: "c", text: "speeds" }, { label: "d", text: "to speed" }],
    answer: "a",
    explanation: "'Let's + 동사원형': Let's 뒤에는 반드시 동사원형이 옵니다. 'speed things up'은 '속도를 높이다'는 의미의 구동사입니다. speeding은 현재분사, speeds는 3인칭 단수, to speed는 to부정사로 Let's 뒤에 쓸 수 없습니다.",
  },
  {
    id: 76, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I've been studying nonstop for three days.\nB: You should take a break. You'll burn _____ if you keep pushing yourself.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "up" }, { label: "b", text: "out" }, { label: "c", text: "off" }, { label: "d", text: "through" }],
    answer: "b",
    explanation: "'burn out'은 '(과로로) 기력이 소진되다, 번아웃되다'는 구동사입니다. burn up은 타서 없어지다, burn off는 소모하다, burn through는 빠르게 소진하다는 의미로 과로 맥락에 맞지 않습니다.",
  },
  {
    id: 77, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Are you sure the building is safe to enter?\nB: It _____ inspected and cleared just yesterday.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "is" }, { label: "b", text: "has" }, { label: "c", text: "was" }, { label: "d", text: "had" }],
    answer: "c",
    explanation: "어제 점검을 받았다는 과거 수동태가 필요합니다. 'It was inspected and cleared just yesterday'에서 was가 수동태 be동사입니다. is는 현재 수동, has는 현재완료 능동이 되어 수동 의미를 나타내지 못합니다.",
  },
  {
    id: 78, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: I'm thinking of applying for the managerial position.\nB: Go for it! You're more than _____ for the role.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "capable" }, { label: "b", text: "capable enough" }, { label: "c", text: "qualified" }, { label: "d", text: "qualified enough" }],
    answer: "d",
    explanation: "'more than qualified enough'는 '충분히 자격을 갖추고도 남는다'는 표현입니다. qualified는 자격/능력 요건 충족을 의미하며, enough를 더해 충분함을 강조합니다. 'more than capable'도 유사하지만 직책 자격 요건에는 qualified가 더 적합합니다.",
  },
  {
    id: 79, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: Should we email the client or call them directly?\nB: Given the urgency, I'd suggest _____ them right away.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "call" }, { label: "b", text: "to call" }, { label: "c", text: "calling" }, { label: "d", text: "called" }],
    answer: "c",
    explanation: "'suggest + 동명사(-ing)': suggest는 목적어로 동명사를 취합니다. 'suggest calling them'이 올바른 형태입니다. to부정사(to call)나 동사원형(call)은 suggest의 목적어로 쓰이지 않습니다.",
  },
  {
    id: 80, part: "I", partLabel: "대화 빈칸 채우기",
    passage: "A: The budget for the event has been cut in half.\nB: Really? That means we'll have to make do with _____ we have.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "which" }, { label: "b", text: "that" }, { label: "c", text: "what" }, { label: "d", text: "whatever" }],
    answer: "d",
    explanation: "'make do with whatever we have'는 '있는 것으로 어떻게든 해결하다'는 의미입니다. whatever는 복합관계대명사로 불확정적 맥락에서 what보다 자연스럽습니다. which는 선행사가 필요하고, that은 여기서 관계대명사로 쓰이기 어렵습니다.",
  },

  // ──────────────── PART II : 추가 문장 빈칸 채우기 (Q81~100) ────────────────
  {
    id: 81, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The committee _____ the report before publishing it to ensure accuracy.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "reviewing" }, { label: "b", text: "reviewed" }, { label: "c", text: "to review" }, { label: "d", text: "has reviewing" }],
    answer: "b",
    explanation: "주어 'The committee'에 대한 서술어로 과거 시제 본동사가 필요합니다. 'reviewed the report'가 과거 사실을 나타내는 주절의 본동사입니다. reviewing은 현재분사로 본동사 역할 불가, to review는 부정사, has reviewing은 비문법적입니다.",
  },
  {
    id: 82, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The findings of the study were so surprising that they left many researchers _____ for words.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "search" }, { label: "b", text: "to search" }, { label: "c", text: "searched" }, { label: "d", text: "searching" }],
    answer: "d",
    explanation: "'leave + 목적어 + 현재분사(-ing)'는 '~가 ~하는 상태로 남겨두다'는 구조입니다. 'left many researchers searching for words'는 '많은 연구자들이 말문이 막히게 했다'는 의미입니다. search(원형), to search(부정사), searched(수동 과거분사)는 이 구조에 맞지 않습니다.",
  },
  {
    id: 83, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Not until the company released its financial report _____ the extent of its losses become public.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "did" }, { label: "b", text: "has" }, { label: "c", text: "was" }, { label: "d", text: "had" }],
    answer: "a",
    explanation: "'Not until + 구/절' 도치: 부정어 Not until이 문두에 오면 주절에서 주어-조동사 도치가 일어납니다. 'Not until A did B'는 'A 이후에야 비로소 B했다'는 의미입니다. 과거 시제 도치이므로 did가 정답입니다.",
  },
  {
    id: 84, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The mayor insisted that the new park _____ open to the public free of charge.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "remain" }, { label: "b", text: "remains" }, { label: "c", text: "remaining" }, { label: "d", text: "to remain" }],
    answer: "a",
    explanation: "'요구/주장 동사 + that + 주어 + 동사원형(가정법 현재)': insist 뒤 that절에는 동사원형을 씁니다. 주어가 'the new park'(3인칭 단수)여도 동사원형 remain을 씁니다. remains는 직설법 현재, remaining은 분사, to remain은 부정사입니다.",
  },
  {
    id: 85, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Rarely _____ such a close collaboration between two rival companies been attempted in the industry.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "is" }, { label: "b", text: "has" }, { label: "c", text: "does" }, { label: "d", text: "was" }],
    answer: "b",
    explanation: "'Rarely + 조동사 + 주어': 부정 부사 Rarely가 문두에 오면 주어-조동사 도치가 일어납니다. 주어 'such a close collaboration'은 단수이며 현재완료 수동태이므로 'Rarely has ~ been attempted'가 맞습니다. is는 단순 현재, does는 단순 현재 도치, was는 과거 도치입니다.",
  },
  {
    id: 86, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The grant is available to any researcher _____ project addresses issues of global health inequality.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "who" }, { label: "b", text: "whom" }, { label: "c", text: "whose" }, { label: "d", text: "which" }],
    answer: "c",
    explanation: "'관계대명사 whose + 명사': whose는 소유격 관계대명사로 선행사(researcher)의 소유물인 project를 나타냅니다. 'researcher whose project addresses'에서 whose가 researcher와 project를 연결합니다. who는 주격, whom은 목적격, which는 사람이 아닌 사물에 씁니다.",
  },
  {
    id: 87, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The novel is set in a dystopian future _____ citizens are monitored by the government at all times.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "where" }, { label: "b", text: "which" }, { label: "c", text: "that" }, { label: "d", text: "when" }],
    answer: "a",
    explanation: "'future'를 선행사로 하는 관계부사 where: 장소나 상황·배경을 나타내는 명사 뒤에 관계부사 where를 씁니다. 'a dystopian future where citizens are monitored'는 '시민들이 감시되는 디스토피아적 미래'를 의미합니다. which는 관계대명사, when은 시간입니다.",
  },
  {
    id: 88, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The architect's design, _____ praised by critics, was ultimately rejected by the city council.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "wide" }, { label: "b", text: "widely" }, { label: "c", text: "wider" }, { label: "d", text: "widest" }],
    answer: "b",
    explanation: "과거분사 'praised'를 수식하는 부사 widely가 필요합니다. 'widely praised'는 '널리 칭찬받은'이라는 의미입니다. wide는 형용사(넓은), wider/widest는 비교급/최상급으로 과거분사를 수식하는 부사 역할을 할 수 없습니다.",
  },
  {
    id: 89, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "It is essential that every employee _____ the new safety guidelines before operating the machinery.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "reads" }, { label: "b", text: "read" }, { label: "c", text: "reading" }, { label: "d", text: "to read" }],
    answer: "b",
    explanation: "'형용사 essential + that + 주어 + 동사원형': 당위성을 나타내는 형용사(essential/important/necessary) 뒤 that절에는 가정법 현재(동사원형)를 씁니다. every employee가 단수여도 reads(직설법)가 아닌 동사원형 read를 씁니다.",
  },
  {
    id: 90, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Given _____ circumstances, the decision to postpone the event was entirely reasonable.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "a" }, { label: "b", text: "the" }, { label: "c", text: "these" }, { label: "d", text: "those" }],
    answer: "c",
    explanation: "'Given + 명사'는 '~을 고려하면'이라는 분사구문입니다. 현재의 특정 상황들을 가리키므로 지시형용사 these(이러한)가 적합합니다. those는 멀리 있는 것을 가리키고, a는 단수 불특정 명사 앞에, the는 이미 알려진 것 앞에 씁니다.",
  },
  {
    id: 91, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The scientist was recognized not only for her research _____ for her contributions to science education.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "but also" }, { label: "b", text: "but yet" }, { label: "c", text: "as well" }, { label: "d", text: "and also" }],
    answer: "a",
    explanation: "'not only A but also B': A뿐만 아니라 B도. not only와 짝을 이루는 상관접속사는 but also입니다. 'not only for her research but also for her contributions'가 병렬 구조를 이룹니다. but yet, as well, and also는 not only와 상관접속사 쌍을 이루지 않습니다.",
  },
  {
    id: 92, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The older the technology, _____ it is to maintain without specialized expertise.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "more difficult" }, { label: "b", text: "the more difficult" }, { label: "c", text: "most difficult" }, { label: "d", text: "the most difficult" }],
    answer: "b",
    explanation: "'The + 비교급 ~, the + 비교급 ~': '~하면 할수록 더 ~하다'는 비례 구문에서 두 절 모두 'the + 비교급'이 필요합니다. 'The older the technology, the more difficult it is'가 올바른 구조입니다. 관사 the 없이 'more difficult'만 쓰면 비문법적입니다.",
  },
  {
    id: 93, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The professor made his students _____ their essays three times before accepting the final draft.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "rewrite" }, { label: "b", text: "to rewrite" }, { label: "c", text: "rewriting" }, { label: "d", text: "rewritten" }],
    answer: "a",
    explanation: "'사역동사 make + 목적어 + 동사원형': make가 사역 동사로 쓰일 때 목적보어는 동사원형입니다. 'made his students rewrite'가 올바른 구조입니다. to rewrite(부정사), rewriting(현재분사)은 make의 목적보어로 쓰이지 않습니다.",
  },
  {
    id: 94, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "We were surprised to find that the house had _____ furnished when we moved in.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "already been" }, { label: "b", text: "been already" }, { label: "c", text: "already" }, { label: "d", text: "been" }],
    answer: "a",
    explanation: "부사 already는 조동사와 과거분사 사이에 위치합니다. 'had already been furnished'에서 already는 had와 been 사이에 옵니다. 'been already furnished'는 already의 위치가 잘못됐고, already나 been만으로는 의미가 불완전합니다.",
  },
  {
    id: 95, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The company _____ have informed its employees earlier about the upcoming layoffs.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "could" }, { label: "b", text: "ought to" }, { label: "c", text: "should" }, { label: "d", text: "might" }],
    answer: "b",
    explanation: "'ought to have + p.p.'는 '~했어야 했는데(하지 않았다)'는 과거에 대한 도덕적 의무와 후회를 나타냅니다. 직원들에게 미리 알렸어야 했다는 도덕적 책임을 강조합니다. could have는 능력/가능성, might have는 약한 추측을 나타냅니다.",
  },
  {
    id: 96, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "Whoever _____ responsible for the leak will be subject to disciplinary action.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "is found" }, { label: "b", text: "was found" }, { label: "c", text: "finds" }, { label: "d", text: "found" }],
    answer: "a",
    explanation: "Whoever가 이끄는 명사절의 술어로 현재의 규정을 나타내야 합니다. 'is found responsible'은 'be found + 형용사'의 현재 수동태 구조입니다. was found는 과거, finds는 능동태, found만으로는 조동사 없이 본동사로 부적절합니다.",
  },
  {
    id: 97, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The accused was acquitted on the grounds that there was _____ evidence to support the charges.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "insufficient" }, { label: "b", text: "enough" }, { label: "c", text: "plenty of" }, { label: "d", text: "ample" }],
    answer: "a",
    explanation: "'acquitted on the grounds that there was insufficient evidence'는 '불충분한 증거'로 무죄가 됐다는 의미입니다. 무죄 판결 이유에는 증거 부족이 필요합니다. enough/plenty of/ample은 모두 '충분한' 증거를 뜻해 맥락과 반대됩니다.",
  },
  {
    id: 98, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The delegation arrived at the summit _____ a clear set of objectives they hoped to achieve.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "with" }, { label: "b", text: "at" }, { label: "c", text: "for" }, { label: "d", text: "by" }],
    answer: "a",
    explanation: "'arrive with + 명사'는 '~을 가지고 도착하다'는 의미입니다. 'arrived with a clear set of objectives'는 '명확한 목표를 가지고 도착했다'를 뜻합니다. at은 도착 장소(arrive at), for는 목적/이유, by는 수단을 나타냅니다.",
  },
  {
    id: 99, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "She felt as though she _____ in a dream when she finally held the championship trophy.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "is" }, { label: "b", text: "was" }, { label: "c", text: "were" }, { label: "d", text: "had been" }],
    answer: "c",
    explanation: "'as though + 가정법': 사실이 아닌 가상 상황이므로 가정법을 씁니다. 현재 시점의 가상 상황에는 가정법 과거(were)를 씁니다. she가 단수여도 were를 쓰는 것이 격식체 가정법입니다. was는 비격식체이지만 시험에서는 were가 정답입니다.",
  },
  {
    id: 100, part: "II", partLabel: "문장 빈칸 채우기",
    passage: "The manager asked that the final report _____ submitted no later than Friday afternoon.",
    question: "빈칸에 들어갈 가장 알맞은 것을 고르시오.",
    options: [{ label: "a", text: "is" }, { label: "b", text: "was" }, { label: "c", text: "be" }, { label: "d", text: "will be" }],
    answer: "c",
    explanation: "'요구 동사 ask that + 주어 + 동사원형(가정법 현재)': ask(요청하다) 뒤 that절에는 동사원형을 씁니다. 수동태이므로 'be submitted'가 정답입니다. is(현재 직설법), was(과거 직설법), will be(미래)는 가정법 현재를 요구하는 that절에 쓰지 않습니다.",
  },

  // ──────────────── PART III : 추가 오류 문장 찾기 (Q101~120) ────────────────
  {
    id: 101, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: Have you ever been to Japan?\n(b) B: Yes, I visited Tokyo last year and was totally amazed by it.\n(c) A: I heard the food there is incredible. What did you like most?\n(d) B: The ramen was out of this world. I miss eating it every single days.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "d",
    explanation: "(d)에서 'every single days'가 오류입니다. every 뒤에는 반드시 단수명사가 오므로 'every single day'로 써야 합니다. every는 단수 취급하는 한정사로 복수명사와 함께 쓸 수 없습니다.",
  },
  {
    id: 102, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) The rise of remote work has dramatically reshaped how companies operate around the world. (b) Many organizations have discovered that productivity can be maintaining even without employees being physically present. (c) However, some managers argue that in-person collaboration fosters creativity in ways that virtual meetings cannot. (d) As a result, many firms have adopted hybrid models that blend remote and in-office work.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "b",
    explanation: "(b)에서 'can be maintaining'이 오류입니다. 수동태는 'be + 과거분사'여야 하므로 'can be maintained'로 고쳐야 합니다. 'be maintaining'은 능동 진행형으로 수동 의미를 나타낼 수 없습니다.",
  },
  {
    id: 103, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) Coral reefs, often called the rainforests of the sea, support an astonishing diversity of marine life. (b) They provide essential habitats, food sources, and breeding grounds for thousands of species. (c) Despite their importance, coral reefs are experiencing widespread die-offs due to ocean warming. (d) Scientists warn that without immediate action, more than half of the world's reefs could vanish by the end of this century.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "a",
    explanation: "(a)에서 'often called the rainforests of the sea'가 어색합니다. 관계절 'which are often called the rainforests of the sea'로 써야 더 명확합니다. 또한 비유적 별칭에는 called보다 'referred to as'가 더 자연스럽습니다.",
  },
  {
    id: 104, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: I just got back from my first camping trip and it was amazing.\n(b) B: Really? I've always wanted to go. Did you have all the right equipment?\n(c) A: Mostly, but I forgot to bring a sleeping bag and ended up to freeze at night.\n(d) B: Oh no! That must have been really uncomfortable.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "c",
    explanation: "(c)에서 'ended up to freeze'가 오류입니다. 'end up + 동명사(-ing)'가 올바른 구조입니다. 'ended up freezing at night'으로 고쳐야 합니다. end up 뒤에 to부정사는 쓰이지 않습니다.",
  },
  {
    id: 105, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) Sleep deprivation has been linked to a wide range of physical and mental health problems. (b) Research indicates that people who consistently sleep fewer than six hours a night are at greater risk for chronic conditions. (c) Lack of sleep can also impair cognitive function, making it difficult to concentrate or make sound decisions. (d) Despite knowing these risks, many people still sacrifice their sleep in order to meet the demands of their busy schedules.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "b",
    explanation: "(b)에서 'at greater risk for chronic conditions'에서 전치사 for 대신 of를 써야 합니다. 'at greater risk of chronic conditions'가 올바른 표현입니다. risk of는 특정 상태가 될 가능성을 나타내며, 만성 질환 발병 위험에는 of가 더 적합합니다.",
  },
  {
    id: 106, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: Did you hear that the café on Main Street is closing down?\n(b) B: Yes, I saw the notice on their window. It's such a shame.\n(c) A: I know. I've been going there ever since I had moved to this neighborhood.\n(d) B: Me too. I'll really miss their homemade pastries.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "c",
    explanation: "(c)에서 'ever since I had moved'가 오류입니다. 'ever since'는 과거부터 현재까지 이어지는 상황과 함께 쓰이며, since절에는 단순과거 'I moved'를 씁니다. had moved(과거완료)는 현재완료진행과 함께 쓰는 since절에 부적합합니다.",
  },
  {
    id: 107, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) The global demand for electric vehicles has been growing steadily over the past decade. (b) Major automakers are investing heavily in battery technology to extend the range of their electric models. (c) Governments in many countries have introduced incentives such as tax credits to encouraging consumers to switch. (d) Despite these efforts, concerns about charging infrastructure remain a significant barrier to widespread adoption.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "c",
    explanation: "(c)에서 'to encouraging consumers'가 오류입니다. to부정사의 to 뒤에는 동사원형이 와야 하므로 'to encourage consumers to switch'로 고쳐야 합니다. encouraging은 동명사/현재분사로 to부정사의 to 뒤에 쓸 수 없습니다.",
  },
  {
    id: 108, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: I'm thinking about starting my own business, but I'm not sure where to begin.\n(b) B: You should consider attend some entrepreneurship workshops first.\n(c) A: That's a good idea. Do you know of any good ones in the area?\n(d) B: There's a great one at the community center every month.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "b",
    explanation: "(b)에서 'consider attend'가 오류입니다. 'consider + 동명사(-ing)': consider 뒤에는 동명사가 옵니다. 'consider attending some entrepreneurship workshops'로 고쳐야 합니다. 동사원형(attend)은 consider의 목적어로 쓰이지 않습니다.",
  },
  {
    id: 109, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) Historians have long debated the true causes of the decline of the Roman Empire. (b) Some argue that internal political instability and corruption weakened its institutions over centuries. (c) Others point to external pressures from migrating peoples as the primary cause of Rome's collapse. (d) Whatever the reasons, the fall of Rome marked the end of ancient history and the beginning the medieval era.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "d",
    explanation: "(d)에서 'the beginning the medieval era'가 오류입니다. 전치사 of가 빠졌으며 'the beginning of the medieval era'로 써야 합니다. 'the beginning + of + 명사'가 올바른 구조입니다.",
  },
  {
    id: 110, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: How was your experience at the new Italian restaurant?\n(b) B: Wonderful! The pasta was cooked perfect and the service was impeccable.\n(c) A: I've been meaning to go there. Is it expensive?\n(d) B: Moderately priced, I'd say. Worth every penny.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "b",
    explanation: "(b)에서 'cooked perfect'가 오류입니다. 동사 cooked를 수식하는 것은 부사여야 하므로 'cooked perfectly'로 써야 합니다. perfect는 형용사이므로 동사를 직접 수식할 수 없습니다.",
  },
  {
    id: 111, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) The ancient Silk Road connected civilizations across Asia, the Middle East, and Europe for centuries. (b) It served as a conduit not only for goods like silk and spices, but also for cultural exchange and ideas. (c) Merchants who traveled these routes often faced extreme hardships, included harsh weather and bandits. (d) Nevertheless, the Silk Road played a pivotal role in shaping the modern world through increased connectivity.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "c",
    explanation: "(c)에서 'hardships, included harsh weather and bandits'가 오류입니다. '포함하여'는 현재분사 'including'을 써야 합니다. 'hardships, including harsh weather and bandits'가 올바른 표현입니다. included는 수동 의미의 과거분사입니다.",
  },
  {
    id: 112, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: I finally convinced my parents to let me study abroad for a semester.\n(b) B: That's fantastic! Where are you planning to go?\n(c) A: I'm leaning towards Spain. I've always wanted to improved my Spanish.\n(d) B: Madrid or Barcelona? Both are incredible cities.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "c",
    explanation: "(c)에서 'wanted to improved my Spanish'가 오류입니다. 'want to + 동사원형'이 맞으므로 'want to improve my Spanish'로 써야 합니다. to부정사의 to 뒤에는 동사원형이 와야 하며, improved는 과거형/과거분사입니다.",
  },
  {
    id: 113, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) Advances in artificial intelligence are transforming industries at an unprecedented pace. (b) From healthcare diagnostics to autonomous vehicles, AI applications are becoming increasingly sophisticated. (c) Critics caution that rapid deployment of AI systems without proper oversight could lead to unintended consequences. (d) To address these concerns, regulators around the world have begun to developed comprehensive AI governance frameworks.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "d",
    explanation: "(d)에서 'have begun to developed'가 오류입니다. 'begin to + 동사원형'이 맞으므로 'have begun to develop'으로 써야 합니다. to부정사의 to 뒤에는 동사원형이 와야 하며, developed는 과거형/과거분사입니다.",
  },
  {
    id: 114, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: I heard the city is planning to build a new sports complex.\n(b) B: Yes, it's been in the news all week. The mayor announced it yesterday.\n(c) A: I think it's a great idea. We really need more recreational space for residents.\n(d) B: I agree, though some people worry about where the fund for it will come from.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "d",
    explanation: "(d)에서 'the fund for it'이 어색합니다. 여러 재원을 가리키므로 복수형 'the funds for it'이 더 적합합니다. 또는 재정 지원 전반을 가리키는 'the funding for it'으로 쓰는 것이 자연스럽습니다.",
  },
  {
    id: 115, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) The Amazon rainforest is one of the most biodiverse regions on Earth. (b) It is home to roughly 10% of all species on the planet, many of which have yet to be discovered. (c) Deforestation poses a serious threat to this ecosystem and the countless organisms that depending on it. (d) Conservation efforts have intensified in recent years, but experts warn that more urgent action is needed.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "c",
    explanation: "(c)에서 'organisms that depending on it'이 오류입니다. 관계절의 동사는 정형동사여야 하므로 'that depend on it'으로 써야 합니다. depending은 현재분사로 관계절에서 정형동사 역할을 할 수 없습니다.",
  },
  {
    id: 116, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: I've been really stressed out about the upcoming board presentation.\n(b) B: Try not to worry too much. You've prepared thoroughly and know the material well.\n(c) A: I suppose so. I just hope everything goes as planned.\n(d) B: It will. Just remember to breathe and speaking clearly when you're up there.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "d",
    explanation: "(d)에서 'breathe and speaking clearly'가 오류입니다. 등위접속사 and로 연결된 병렬 구조에서 'breathe and speak clearly'로 써야 합니다. 'remember to breathe and (to) speak clearly'가 올바른 병렬 구조입니다.",
  },
  {
    id: 117, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) The concept of universal basic income has gained traction as automation continues to displace workers. (b) Proponents argue that a monthly stipend would provide financial security and reduce poverty levels. (c) Critics, however, contend that such a system would be too costly and might reduce the incentive working. (d) Pilot programs in several countries have yielded mixed results, with outcomes varying widely by region.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "c",
    explanation: "(c)에서 'reduce the incentive working'이 오류입니다. 'incentive to + 동사원형'이 올바른 구조이므로 'reduce the incentive to work'로 써야 합니다. incentive 뒤에는 to부정사가 오며, working(동명사/분사)은 쓰이지 않습니다.",
  },
  {
    id: 118, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: Our team's performance in the first quarter has been disappointing.\n(b) B: I agree. We need to identify what's been holding us back.\n(c) A: I think the main issue is that we haven't been communicated clearly enough with each other.\n(d) B: You're right. Let's schedule a team meeting to address these problems.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "c",
    explanation: "(c)에서 'haven't been communicated clearly enough'가 오류입니다. communicate는 자동사로도 쓰이므로 'haven't been communicating clearly enough'(현재완료진행 능동) 또는 'haven't communicated clearly enough'로 써야 합니다. 'been communicated'는 수동태로 의미가 달라집니다.",
  },
  {
    id: 119, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) Online learning platforms have become increasingly popular since the pandemic began. (b) Many students appreciate the flexibility they offer, allowing them to learn at their own pace. (c) However, some educators argue that the lack of face-to-face interaction can hinder the development of critical thinking. (d) Despite these concerns, the number of students enrolled in online courses have continued to grow each year.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "d",
    explanation: "(d)에서 'the number of students... have continued'가 오류입니다. 'the number of + 복수명사'는 단수 취급하므로 'has continued'로 써야 합니다. 'a number of students'는 복수로 취급하지만 'the number of students'는 단수입니다.",
  },
  {
    id: 120, part: "III", partLabel: "오류 문장 찾기",
    passage: "(a) A: I just read that the city plans to ban single-use plastics by next year.\n(b) B: It's about time. We've been producing far too much plastic waste.\n(c) A: Agreed. Hopefully other cities will follow suit and adopt similar policies.\n(d) B: I think they will eventually, but change often takes longer as we'd like.",
    question: "어색한 표현이나 문법 오류가 포함된 것을 고르시오.",
    options: [{ label: "a", text: "(a)" }, { label: "b", text: "(b)" }, { label: "c", text: "(c)" }, { label: "d", text: "(d)" }],
    answer: "d",
    explanation: "(d)에서 'takes longer as we'd like'가 오류입니다. 비교급 longer 뒤에는 비교 대상을 도입하는 'than'이 와야 하므로 'takes longer than we'd like'로 써야 합니다. as는 동등 비교(as ~ as)에 씁니다.",
  },
];
